(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],modal=$('#modal'),mb=$('#mb');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n||0).toLocaleString('id-ID');
function openModal(title,html){if(!modal||!mb)return;mb.innerHTML='<h2>'+esc(title)+'</h2>'+html;modal.classList.add('open')}
function closeModal(){modal?.classList.remove('open')}
$('#close')?.addEventListener('click',closeModal);modal?.addEventListener('click',e=>{if(e.target===modal)closeModal()});
let portal=null;
const SUPABASE_URL='https://gfggmkeucgqkkyvummpu.supabase.co';
const SUPABASE_KEY='sb_publishable_ptCVbq9h15prKhT0OO5Zmg_LkE3cbw0';
const sb=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
let session=null;
async function getSession(){if(!sb)return null;const r=await sb.auth.getSession();session=r.data.session||null;return session}
function authHeaders(){return session?.access_token?{Authorization:'Bearer '+session.access_token}:{} }
function renderAuth(){const a=$('#authArea');if(!a)return;const label=session?.user?.email||'Pengunjung';const sub=session?'Akun aktif · Laporan Saya':'Masuk / Daftar';a.innerHTML='<span class="bell">♧<b>3</b></span><button class="authBtn" id="authBtn" type="button"><span class="avatar">●</span><span><strong>'+esc(label)+'</strong><small>'+esc(sub)+'</small></span></button>';$('#authBtn')?.addEventListener('click',authPanel)}
function authPanel(mode='login'){
if(session){
openModal('Akun Saya','<p><b>'+esc(session.user.email||'')+'</b></p><p class="authNote">Akses data pribadi dibatasi ke akun ini. Admin/moderator memproses laporan sesuai kewenangan.</p><div class="authLinks"><button class="outline" id="myReportsBtn">Laporan Saya</button><button class="outline" id="logoutBtn">Keluar</button></div>');
$('#logoutBtn')?.addEventListener('click',async()=>{await sb.auth.signOut();session=null;renderAuth();closeModal();loadPortal()});
$('#myReportsBtn')?.addEventListener('click',()=>{const rows=portal?.tables?.my_citizen_reports||[];openModal('Laporan Saya',rows.length?rows.map(x=>'<div class="rankrow"><span>●</span><span><b>'+esc(x.title||'Tanpa judul')+'</b><br><small>'+esc(x.category||'')+' · '+esc(x.verification_status||'unverified')+'</small></span><strong>'+esc(x.reported_at||'')+'</strong></div>').join(''):'<p>Belum ada laporan dari akun ini.</p>')});
return;
}
const isSignup=mode==='signup';
const title=isSignup?'Buat Akun Baru':'Masuk ke Akun';
const html=isSignup?'<form class="authForm" id="authForm"><div class="authTwo"><input name="first_name" required maxlength="80" placeholder="Nama Depan"><input name="last_name" maxlength="80" placeholder="Nama Belakang"></div><input name="identifier" type="text" required autocomplete="username" placeholder="Nomor Ponsel atau Email"><div class="passwordWrap"><input id="authPassword" type="password" name="password" required minlength="6" autocomplete="new-password" placeholder="Kata Sandi Baru" style="padding-right:48px"><button type="button" id="togglePassword" aria-label="Tampilkan password" title="Tampilkan password" style="position:absolute;right:10px;top:50%;transform:translateY(-50%);border:0;background:transparent;cursor:pointer;font-size:20px;line-height:1">👁️</button></div><div class="authThree"><select name="birth_day" required><option value="">Hari</option>'+Array.from({length:31},(_,i)=>'<option value="'+(i+1)+'">'+(i+1)+'</option>').join('')+'</select><select name="birth_month" required><option value="">Bulan</option>'+['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'].map((m,i)=>'<option value="'+(i+1)+'">'+m+'</option>').join('')+'</select><select name="birth_year" required><option value="">Tahun</option>'+Array.from({length:100},(_,i)=>{const y=new Date().getFullYear()-i;return '<option value="'+y+'">'+y+'</option>'}).join('')+'</select></div><div class="gender"><span>Jenis Kelamin:</span><label><input type="radio" name="gender" value="female" required> Perempuan</label><label><input type="radio" name="gender" value="male"> Laki-laki</label><label><input type="radio" name="gender" value="custom"> Khusus (Custom)</label></div><p class="privacy">Dengan mengklik Daftar, Anda menyetujui Ketentuan, Kebijakan Privasi, dan Kebijakan Cookie kami.</p><button class="cta" type="submit">Daftar</button><button class="outline" type="button" id="switchAuth">Sudah punya akun? Login / Masuk</button><p class="authNote" id="authMsg">Gunakan email untuk pendaftaran agar konfirmasi akun dapat dikirim melalui email.</p></form>'
:'<form class="authForm" id="authForm"><input name="identifier" type="text" required autocomplete="username" placeholder="Email atau Nomor Telepon"><div class="passwordWrap"><input id="authPassword" type="password" name="password" required minlength="6" autocomplete="current-password" placeholder="Kata Sandi" style="padding-right:48px"><button type="button" id="togglePassword" aria-label="Tampilkan password" title="Tampilkan password" style="position:absolute;right:10px;top:50%;transform:translateY(-50%);border:0;background:transparent;cursor:pointer;font-size:20px;line-height:1">👁️</button></div><button class="cta" type="submit">Login / Masuk</button><button class="outline" type="button" id="forgotBtn">Lupa Kata Sandi?</button><button class="outline" type="button" id="switchAuth">Buat Akun Baru</button><p class="authNote" id="authMsg">Masuk menggunakan email atau nomor telepon yang terdaftar.</p></form>';
openModal(title,html);
const pw=$('#authPassword'),tp=$('#togglePassword');
tp?.addEventListener('click',()=>{const show=pw?.type==='password';if(pw)pw.type=show?'text':'password';if(tp){tp.textContent=show?'🙈':'👁️';tp.setAttribute('aria-label',show?'Sembunyikan password':'Tampilkan password')}});
$('#switchAuth')?.addEventListener('click',()=>authPanel(isSignup?'login':'signup'));
$('#forgotBtn')?.addEventListener('click',()=>forgotPassword());
$('#authForm')?.addEventListener('submit',async e=>{
e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const m=$('#authMsg');m.textContent='Memproses...';
if(isSignup){
if(!f.identifier.includes('@')){m.textContent='Untuk pendaftaran saat ini gunakan alamat email. Login nomor telepon memerlukan layanan SMS Supabase.';return}
const birth=f.birth_year+'-'+String(f.birth_month).padStart(2,'0')+'-'+String(f.birth_day).padStart(2,'0');
const r=await sb.auth.signUp({email:f.identifier,password:f.password,options:{emailRedirectTo:window.location.origin+'/',data:{first_name:f.first_name,last_name:f.last_name,birth_date:birth,gender:f.gender}}});
if(r.error){m.textContent=r.error.message;return}
m.textContent=r.data.session?'Akun aktif.':'Pendaftaran berhasil. Cek email Anda untuk konfirmasi akun sebelum login.';
}else{
if(f.identifier.includes('@')){
const r=await sb.auth.signInWithPassword({email:f.identifier,password:f.password});if(r.error){m.textContent=r.error.message;return}
session=r.data.session;renderAuth();closeModal();loadPortal();
}else{m.textContent='Login nomor telepon memerlukan SMS Auth yang harus diaktifkan di Supabase. Untuk sekarang gunakan email.'}
}});
}
async function forgotPassword(){
openModal('Lupa Kata Sandi','<form class="authForm" id="resetForm"><input id="resetEmail" type="email" required placeholder="Email akun Anda"><button class="cta" type="submit">Kirim Tautan Reset</button><p class="authNote" id="resetMsg">Kami akan mengirim tautan untuk membuat kata sandi baru.</p></form>');
$('#resetForm')?.addEventListener('submit',async e=>{e.preventDefault();const email=$('#resetEmail').value.trim(),m=$('#resetMsg');m.textContent='Mengirim...';const r=await sb.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+'/#reset-password'});m.textContent=r.error?r.error.message:'Tautan reset sudah dikirim. Periksa email Anda.'});
}

function initLiveProblemMap(rows=[]){
 const el=$('.mapbox'); if(!el||!window.L)return;
 el.innerHTML='<div class="mapTools"><button class="mapLayer active" data-layer="street">Peta</button><button class="mapLayer" data-layer="satellite">Satelit</button><span class="mapLive">● LIVE</span></div><div class="mapLegend"><b>Peta Masalah & Kejadian</b><span>🔴 Resmi</span><span>🟠 Berita</span><span>🔵 Laporan</span></div>';
 const map=L.map(el,{scrollWheelZoom:false}).setView([-2.5,118],4.6);
 const street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);
 const satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution:'Tiles © Esri'});
 const layer=L.layerGroup().addTo(map);
 const color=r=>r.source_type==='official_disaster'||r.source_type==='official_seismic'?'red':r.source_type==='news_signal'?'orange':'blue';
 rows.filter(r=>Number.isFinite(Number(r.latitude))&&Number.isFinite(Number(r.longitude))).forEach(r=>{
   const cls=color(r);
   const icon=L.divIcon({className:'live-marker-wrap',html:'<span class="live-marker '+cls+'"></span>',iconSize:[18,18],iconAnchor:[9,9]});
   const precision=r.metadata?.location_precision==='exact'?'Koordinat sumber':'Perkiraan pusat wilayah';
   const popup='<div class="incidentPopup"><b>'+esc(r.title)+'</b><br><span>'+esc(r.incident_type||'Peristiwa')+' · '+esc(r.status||'unverified')+'</span><hr><b>Lokasi</b><br>'+esc(r.location_text||'Tidak tersedia')+'<br><b>Koordinat</b><br>'+Number(r.latitude).toFixed(5)+', '+Number(r.longitude).toFixed(5)+'<br><small>'+esc(precision)+' · Sumber: '+esc(r.source_name)+'</small>'+(r.source_url?'<br><a href="'+esc(r.source_url)+'" target="_blank" rel="noopener">Buka sumber →</a>':'')+'</div>';
   L.marker([Number(r.latitude),Number(r.longitude)],{icon}).addTo(layer).bindPopup(popup);
 });
 $('.mapLayer').forEach(b=>b.addEventListener('click',()=>{$('.mapLayer').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.layer==='satellite'){map.removeLayer(street);satellite.addTo(map)}else{map.removeLayer(satellite);street.addTo(map)}}));
 setTimeout(()=>map.invalidateSize(),300); window.problemMap=map;
}

async function loadPortal(){try{await getSession();renderAuth();const r=await fetch('/api/portal-data?tables=regions,problems,early_signals,forecasts,solutions,citizen_reports,data_sources&limit=30',{cache:'no-store',headers:authHeaders()});if(!r.ok)throw Error();portal=await r.json();portal.live_incidents=[];try{const lr=await fetch('/api/bmkg?mode=incidents',{cache:'no-store'});const lj=lr.ok?await lr.json():{};portal.live_incidents.push(...(lj.incidents||[]))}catch{}try{const br=await fetch('https://gis.bnpb.go.id/server/rest/services/Kejadian_Bencana_Mingguan/FeatureServer/0/query?where=1%3D1&outFields=*&returnGeometry=true&f=json&resultRecordCount=100&orderByFields=objectid%20DESC',{cache:'no-store'});const bj=br.ok?await br.json():{};(bj.features||[]).forEach(f=>{const a=f.attributes||{},g=f.geometry||{};const lat=Number(g.y),lng=Number(g.x);if(!Number.isFinite(lat)||!Number.isFinite(lng))return;const title=a.kejadian||a.jenis_bencana||a.jenis||a.nama_bencana||'Kejadian bencana';portal.live_incidents.push({source_name:'BNPB',source_type:'official_disaster',source_url:'https://gis.bnpb.go.id/server/rest/services/Kejadian_Bencana_Mingguan/FeatureServer/0',title:String(title),description:String(a.kronologi||a.deskripsi||a.keterangan||a.lokasi||''),incident_type:String(title),status:'official_signal',observed_at:new Date().toISOString(),latitude:lat,longitude:lng,location_text:String(a.lokasi||''),severity:'unknown',confidence_score:.95,location_precision:'exact'})})}catch{}hydrate(portal);return portal}catch(e){console.warn(e);return null}}
function hydrate(d){
const rc=d.region_counts||{};const hs=$$('.heroStat b');if(hs[0])hs[0].textContent=fmt(rc.province)+' Provinsi';if(hs[1])hs[1].textContent=fmt(rc.regency)+' Kabupaten/Kota';if(hs[2])hs[2].textContent=fmt(rc.district)+' Kecamatan';if(hs[3])hs[3].textContent=fmt(rc.village)+' Desa/Kelurahan';
const live=d.live_incidents||[];initLiveProblemMap(live);const problems=d.tables?.problems||[], reports=d.tables?.citizen_reports||[], signals=d.tables?.early_signals||[], forecasts=d.tables?.forecasts||[], solutions=d.tables?.solutions||[];
const issueGrid=$('.issueGrid');if(issueGrid){if(!problems.length&&!reports.length)issueGrid.innerHTML='<div style="grid-column:1/-1;padding:28px;text-align:center;color:#789">Belum ada masalah terbit/terverifikasi di database publik.</div>';else{const rows=[...problems.map(x=>({...x,_type:'problem'})),...reports.map(x=>({...x,_type:'report'}))].sort((a,b)=>new Date(b.updated_at||b.reported_at||0)-new Date(a.updated_at||a.reported_at||0)).slice(0,4);issueGrid.innerHTML=rows.map((x,i)=>'<article class="issue"><img src="/assets/'+(['problem-road.svg','problem-flood.svg','problem-school.svg','problem-health.svg'][i%4])+'" alt=""><div class="issueBody"><div class="badges"><span class="badge blue">'+esc(x.category||'Umum')+'</span><span class="badge">'+esc(x.status||x.verification_status||'Terbit')+'</span></div><h3>'+esc(x.title||'Tanpa judul')+'</h3><p>'+esc(x.severity||'')+' · '+esc(x.updated_at||x.reported_at||'')+'</p></div></article>').join('')}}
const q=$$('.q');const vals=[problems.filter(x=>['active','open','ongoing'].includes(String(x.status||'').toLowerCase())).length,problems.filter(x=>['resolved','closed','completed'].includes(String(x.status||'').toLowerCase())).length,reports.length,solutions.length];q.forEach((el,i)=>{const b=el.querySelector('b');if(b)b.textContent=fmt(vals[i])});
const voice=$('#citizenVoice');if(voice){voice.innerHTML=reports.length?reports.slice(0,3).map(x=>'<div class="rankrow"><span>◉</span><span>'+esc(x.title||'Laporan warga')+'<br><small>'+esc(x.category||'')+' · '+esc(x.reported_at||'')+'</small></span></div>').join(''):'<div class="rankrow"><span>◉</span><span>Belum ada suara warga terverifikasi.</span></div>'}
const rank=$('.rank');if(rank){const counts={};problems.forEach(x=>{const k=x.category||'Lainnya';counts[k]=(counts[k]||0)+1});const sorted=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,5);const rows=sorted.length?sorted.map((x,i)=>'<div class="rankrow"><span class="num">'+(i+1)+'</span><span>'+esc(x[0])+'</span><strong>'+fmt(x[1])+' masalah</strong></div>').join(''):'<div class="rankrow"><span>Belum ada data masalah terbit.</span></div>';rank.querySelectorAll('.rankrow').forEach(x=>x.remove());rank.insertAdjacentHTML('beforeend',rows)}
const trends=$('.trendItems');if(trends)trends.innerHTML=(signals.length?signals.slice(0,4).map(s=>'<div class="rankrow"><span>↗</span><span>'+esc(s.title||s.description||'Sinyal baru')+'</span><strong>'+esc(s.change_percent!=null?s.change_percent+'%':'')+'</strong></div>').join(''):'<div class="rankrow"><span>Belum ada sinyal intelligence yang dipublikasikan.</span></div>');
}
async function search(q){openModal('Mencari…','<p>Mengambil hasil dari database publik.</p>');try{const r=await fetch('/api/search?q='+encodeURIComponent(q),{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error();const all=[...(d.results?.regions||[]).map(x=>['Wilayah',x.name,x.level]),...(d.results?.problems||[]).map(x=>['Masalah',x.title,x.category]),...(d.results?.verified_reports||[]).map(x=>['Suara Warga',x.title,x.category])];openModal('Hasil Pencarian','<p>Kata kunci: <b>'+esc(q)+'</b></p>'+(all.length?'<div>'+all.map(x=>'<div class="rankrow"><span>'+esc(x[0])+'</span><span>'+esc(x[1])+'</span><strong>'+esc(x[2]||'')+'</strong></div>').join('')+'</div>':'<p>Tidak ada hasil publik yang cocok.</p>'))}catch{openModal('Pencarian','<p>Pencarian database sedang tidak tersedia. Silakan coba lagi.</p>')}}
async function report(){await getSession();if(!session){openModal('Login Diperlukan','<p>Untuk menjaga agar setiap laporan dapat diawasi dan ditelusuri oleh admin, silakan masuk atau daftar terlebih dahulu.</p><button class="cta" id="goLogin">Masuk / Daftar →</button>');$('#goLogin')?.addEventListener('click',authPanel);return}openModal('Laporkan Masalah','<p>Laporan publik masuk sebagai <b>unverified</b> dan tidak tampil sebagai fakta terverifikasi sebelum proses verifikasi.</p><form id="rf"><input name="title" required maxlength="240" placeholder="Judul masalah"><input name="region_name" placeholder="Nama wilayah (opsional)"><select name="category"><option>Infrastruktur</option><option>Pendidikan</option><option>Kesehatan</option><option>Lingkungan</option><option>Ekonomi</option><option>Sosial</option></select><select name="severity"><option value="low">Rendah</option><option value="medium" selected>Sedang</option><option value="high">Tinggi</option><option value="critical">Kritis</option></select><textarea name="narrative" required maxlength="10000" placeholder="Jelaskan kejadian, lokasi, waktu, dan dampaknya."></textarea><button class="cta">Kirim Laporan →</button></form>');
$('#rf').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target).entries());const btn=e.target.querySelector('button');btn.disabled=true;try{const r=await fetch('/api/report',{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify(f)}),j=await r.json();if(!r.ok)throw Error();openModal('Laporan Diterima','<p>Laporan tersimpan di Supabase dan menunggu verifikasi.</p><p>ID: <b>'+esc(j.report_id||'diterima')+'</b></p>')}catch{openModal('Laporan Gagal','<p>Laporan belum tersimpan. Periksa koneksi dan coba kembali.</p>')}}}
const content={map:['Peta Indonesia','<p>Peta publik menggunakan geografi nasional dari database dan dapat diperluas dengan filter wilayah, kategori, periode, dan sumber.</p><div class="mapbox"></div>'],data:['Data & Statistik','<p>Modul ini membaca dataset, indikator, periode, kualitas, dan sumber dari portal data.</p><div class="rankrow"><span>Dataset terdaftar</span><strong>'+fmt(portal?.tables?.data_sources?.length)+'</strong></div>'],monitor:['Pantau Perubahan','<p>Modul membaca early signals yang telah dipublikasikan. Sinyal tanpa data tidak dibuat-buat.</p><div class="rankrow"><span>Sinyal tersedia</span><strong>'+fmt(portal?.tables?.early_signals?.length)+'</strong></div>'],insights:['Wawasan & Intelligence','<p>Analisis berbasis claims, evidence, observations, dan sumber. Hasil hanya ditampilkan bila tersedia di sistem.</p>'],forecast:['Kemungkinan / Future Radar','<p>Forecast publik ditampilkan dengan horizon, model, confidence, faktor, dan ketidakpastian ketika data tersedia.</p><div class="rankrow"><span>Forecast tersedia</span><strong>'+fmt(portal?.tables?.forecasts?.length)+'</strong></div>'],solutions:['Solusi','<p>Solusi publik berasal dari tabel solusi dan dapat memuat tipe, dampak, risiko, kelayakan, asumsi, serta outcome.</p><div class="rankrow"><span>Solusi tersedia</span><strong>'+fmt(portal?.tables?.solutions?.length)+'</strong></div>'],about:['Tentang Nuansa Kita','<p>NUANSA KITA — ASPIRASI PUBLIK INDONESIA adalah portal untuk melihat masalah, mendengar suara warga, memahami data, memantau perubahan, mengantisipasi kemungkinan, dan mencari solusi secara transparan.</p>']};
function show(k){const v=content[k]||content.about;openModal(v[0],v[1])}
const actions={map:()=>show('map'),data:()=>show('data'),report,monitor:()=>show('monitor'),insights:()=>show('insights'),forecast:()=>show('forecast'),solutions:()=>show('solutions'),about:()=>show('about')};
$$('[data-act]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();actions[el.dataset.act]?.()}));
$$('.group>button').forEach(btn=>btn.addEventListener('click',()=>btn.parentElement.classList.toggle('open')));
$$('.group .sub a').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const t=a.textContent.trim();const map={'Terkini':'monitor','Berdasarkan Wilayah':'map','Berdasarkan Kategori':'data','Mendesak':'monitor','Belum Terselesaikan':'monitor','Sumber Data':'data','Kumpulan Data':'data','Indikator':'data','Kualitas & Pembaruan Data':'data','Laporkan Masalah':'report','Cerita Warga':'report','Keluhan':'report','Usulan':'report','Polling':'report','Diskusi':'report','Masalah Baru':'monitor','Meningkat':'monitor','Menurun':'monitor','Ramai Dibicarakan':'monitor','Peringatan':'monitor','Pola':'insights','Penyebab':'insights','Tren':'insights','Hubungan':'insights','Ringkasan Wilayah':'insights','Perkiraan':'forecast','Perbandingan':'forecast','Skenario':'forecast','Solusi Warga':'solutions','Solusi Pemerintah':'solutions','Praktik Baik':'solutions','Evaluasi Hasil':'solutions'};actions[map[t]]?.()}));
$$('.cat').forEach(b=>b.addEventListener('click',()=>show('data')));
$('#searchForm')?.addEventListener('submit',e=>{e.preventDefault();const q=$('#q').value.trim();if(q)search(q)});
$$('.map-switch button').forEach(b=>b.addEventListener('click',()=>{$$('.map-switch button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const box=$('.mapbox');if(box)box.style.filter=b.textContent.trim()==='Satelit'?'saturate(.65) brightness(.9)':'none'}));
if(sb){sb.auth.onAuthStateChange((_event,s)=>{session=s||null;renderAuth();});}
loadPortal();
})();