(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],modal=$('#modal'),mb=$('#mb');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n||0).toLocaleString('id-ID');
function openModal(title,html){if(!modal||!mb)return;mb.innerHTML='<h2>'+esc(title)+'</h2>'+html;modal.classList.add('open')}
function closeModal(){modal?.classList.remove('open')}
$('#close')?.addEventListener('click',closeModal);modal?.addEventListener('click',e=>{if(e.target===modal)closeModal()});
let portal=null;
const SUPABASE_URL='https://gfggmkeucgqkkyvummpu.supabase.co';
const SUPABASE_KEY='sb_publishable_ptCVbq9h15prKhT0OO5Zmg_LkE3cbw0';
const sb=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
let session=null;
async function getSession(){if(!sb)return null;const r=await sb.auth.getSession();session=r.data.session||null;return session}
function authHeaders(){return session?.access_token?{Authorization:'Bearer '+session.access_token}:{} }
function renderAuth(){const a=$('#authArea');if(!a)return;const label=session?.user?.email||'Pengunjung';const sub=session?'Akun aktif · Laporan Saya':'Masuk / Daftar';a.innerHTML='<span class="bell">♧<b>3</b></span><button class="authBtn" id="authBtn" type="button"><span class="avatar">●</span><span><strong>'+esc(label)+'</strong><small>'+esc(sub)+'</small></span></button>';$('#authBtn')?.addEventListener('click',authPanel)}
function authPanel(){if(session){openModal('Akun Saya','<p><b>'+esc(session.user.email||'')+'</b></p><p class="authNote">Akses data pribadi dibatasi ke akun ini. Admin/moderator memproses laporan sesuai kewenangan.</p><div class="authLinks"><button class="outline" id="myReportsBtn">Laporan Saya</button><button class="outline" id="logoutBtn">Keluar</button></div>');$('#logoutBtn')?.addEventListener('click',async()=>{await sb.auth.signOut();session=null;renderAuth();closeModal();loadPortal()});$('#myReportsBtn')?.addEventListener('click',()=>{const rows=portal?.tables?.my_citizen_reports||[];openModal('Laporan Saya',rows.length?rows.map(x=>'<div class="rankrow"><span>●</span><span><b>'+esc(x.title||'Tanpa judul')+'</b><br><small>'+esc(x.category||'')+' · '+esc(x.verification_status||'unverified')+'</small></span><strong>'+esc(x.reported_at||'')+'</strong></div>').join(''):'<p>Belum ada laporan dari akun ini.</p>')})}else{openModal('Masuk / Daftar','<form class="authForm" id="authForm"><input type="email" name="email" required placeholder="Email"><div class="passwordWrap"><input id="authPassword" type="password" name="password" required minlength="6" placeholder="Password minimal 6 karakter" style="padding-right:48px"><button type="button" id="togglePassword" aria-label="Tampilkan password" title="Tampilkan password" style="position:absolute;right:10px;top:50%;transform:translateY(-50%);border:0;background:transparent;cursor:pointer;font-size:20px;line-height:1">👁️</button></div><button class="cta" type="submit">Masuk</button><button class="outline" type="button" id="signupBtn">Daftar Akun Baru</button><p class="authNote" id="authMsg">Akun diperlukan untuk mengirim laporan dan melihat laporan milik Anda.</p></form>');const pw=$('#authPassword'),tp=$('#togglePassword');tp?.addEventListener('click',()=>{const show=pw?.type==='password';if(pw)pw.type=show?'text':'password';if(tp){tp.textContent=show?'🙈':'👁️';tp.setAttribute('aria-label',show?'Sembunyikan password':'Tampilkan password');tp.setAttribute('title',show?'Sembunyikan password':'Tampilkan password')}});$('#authForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const m=$('#authMsg');m.textContent='Memproses...';const r=await sb.auth.signInWithPassword({email:f.email,password:f.password});if(r.error){m.textContent=r.error.message;return}session=r.data.session;renderAuth();closeModal();loadPortal()});$('#signupBtn')?.addEventListener('click',async()=>{const f=Object.fromEntries(new FormData($('#authForm')));const m=$('#authMsg');if(!f.email||!f.password){m.textContent='Isi email dan password terlebih dahulu.';return}m.textContent='Mendaftarkan akun...';const r=await sb.auth.signUp({email:f.email,password:f.password});if(r.error){m.textContent=r.error.message;return}m.textContent=r.data.session?'Akun aktif.':'Pendaftaran berhasil. Jika konfirmasi email aktif, cek email Anda.'})}}
async function loadPortal(){try{await getSession();renderAuth();const r=await fetch('/api/portal-data?tables=regions,problems,early_signals,forecasts,solutions,citizen_reports,data_sources&limit=30',{cache:'no-store',headers:authHeaders()});if(!r.ok)throw Error();portal=await r.json();hydrate(portal);return portal}catch(e){console.warn(e);return null}}
function hydrate(d){
const rc=d.region_counts||{};const hs=$$('.heroStat b');if(hs[0])hs[0].textContent=fmt(rc.province)+' Provinsi';if(hs[1])hs[1].textContent=fmt(rc.regency)+' Kabupaten/Kota';if(hs[2])hs[2].textContent=fmt(rc.district)+' Kecamatan';if(hs[3])hs[3].textContent=fmt(rc.village)+' Desa/Kelurahan';
const problems=d.tables?.problems||[], reports=d.tables?.citizen_reports||[], signals=d.tables?.early_signals||[], forecasts=d.tables?.forecasts||[], solutions=d.tables?.solutions||[];
const issueGrid=$('.issueGrid');if(issueGrid){if(!problems.length&&!reports.length)issueGrid.innerHTML='<div style="grid-column:1/-1;padding:28px;text-align:center;color:#789">Belum ada masalah terbit/terverifikasi di database publik.</div>';else{const rows=[...problems.map(x=>({...x,_type:'problem'})),...reports.map(x=>({...x,_type:'report'}))].sort((a,b)=>new Date(b.updated_at||b.reported_at||0)-new Date(a.updated_at||a.reported_at||0)).slice(0,4);issueGrid.innerHTML=rows.map((x,i)=>'<article class="issue"><img src="/assets/'+(['problem-road.svg','problem-flood.svg','problem-school.svg','problem-health.svg'][i%4])+'" alt=""><div class="issueBody"><div class="badges"><span class="badge blue">'+esc(x.category||'Umum')+'</span><span class="badge">'+esc(x.status||x.verification_status||'Terbit')+'</span></div><h3>'+esc(x.title||'Tanpa judul')+'</h3><p>'+esc(x.severity||'')+' · '+esc(x.updated_at||x.reported_at||'')+'</p></div></article>').join('')}}
const q=$$('.q');const vals=[problems.filter(x=>['active','open','ongoing'].includes(String(x.status||'').toLowerCase())).length,problems.filter(x=>['resolved','closed','completed'].includes(String(x.status||'').toLowerCase())).length,reports.length,solutions.length];q.forEach((el,i)=>{const b=el.querySelector('b');if(b)b.textContent=fmt(vals[i])});
const voice=$('#citizenVoice');if(voice){voice.innerHTML=reports.length?reports.slice(0,3).map(x=>'<div class="rankrow"><span>◉</span><span>'+esc(x.title||'Laporan warga')+'<br><small>'+esc(x.category||'')+' · '+esc(x.reported_at||'')+'</small></span></div>').join(''):'<div class="rankrow"><span>◉</span><span>Belum ada suara warga terverifikasi.</span></div>'}
const rank=$('.rank');if(rank){const counts={};problems.forEach(x=>{const k=x.category||'Lainnya';counts[k]=(counts[k]||0)+1});const sorted=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,5);const rows=sorted.length?sorted.map((x,i)=>'<div class="rankrow"><span class="num">'+(i+1)+'</span><span>'+esc(x[0])+'</span><strong>'+fmt(x[1])+' masalah</strong></div>').join(''):'<div class="rankrow"><span>Belum ada data masalah terbit.</span></div>';rank.querySelectorAll('.rankrow').forEach(x=>x.remove());rank.insertAdjacentHTML('beforeend',rows)}
const trends=$('.trendItems');if(trends)trends.innerHTML=(signals.length?signals.slice(0,4).map(s=>'<div class="rankrow"><span>↗</span><span>'+esc(s.title||s.description||'Sinyal baru')+'</span><strong>'+esc(s.change_percent!=null?s.change_percent+'%':'')+'</strong></div>').join(''):'<div class="rankrow"><span>Belum ada sinyal intelligence yang dipublikasikan.</span></div>');
}
async function search(q){openModal('Mencari…','<p>Mengambil hasil dari database publik.</p>');try{const r=await fetch('/api/search?q='+encodeURIComponent(q),{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error();const all=[...(d.results?.regions||[]).map(x=>['Wilayah',x.name,x.level]),...(d.results?.problems||[]).map(x=>['Masalah',x.title,x.category]),...(d.results?.verified_reports||[]).map(x=>['Suara Warga',x.title,x.category])];openModal('Hasil Pencarian','<p>Kata kunci: <b>'+esc(q)+'</b></p>'+(all.length?'<div>'+all.map(x=>'<div class="rankrow"><span>'+esc(x[0])+'</span><span>'+esc(x[1])+'</span><strong>'+esc(x[2]||'')+'</strong></div>').join('')+'</div>':'<p>Tidak ada hasil publik yang cocok.</p>'))}catch{openModal('Pencarian','<p>Pencarian database sedang tidak tersedia. Silakan coba lagi.</p>')}}
async function report(){await getSession();if(!session){openModal('Login Diperlukan','<p>Untuk menjaga agar setiap laporan dapat diawasi dan ditelusuri oleh admin, silakan masuk atau daftar terlebih dahulu.</p><button class="cta" id="goLogin">Masuk / Daftar →</button>');$('#goLogin')?.addEventListener('click',authPanel);return}openModal('Laporkan Masalah','<p>Laporan publik masuk sebagai <b>unverified</b> dan tidak tampil sebagai fakta terverifikasi sebelum proses verifikasi.</p><form id="rf"><input name="title" required maxlength="240" placeholder="Judul masalah"><input name="region_name" placeholder="Nama wilayah (opsional)"><select name="category"><option>Infrastruktur</option><option>Pendidikan</option><option>Kesehatan</option><option>Lingkungan</option><option>Ekonomi</option><option>Sosial</option></select><select name="severity"><option value="low">Rendah</option><option value="medium" selected>Sedang</option><option value="high">Tinggi</option><option value="critical">Kritis</option></select><textarea name="narrative" required maxlength="10000" placeholder="Jelaskan kejadian, lokasi, waktu, dan dampaknya."></textarea><button class="cta">Kirim Laporan →</button></form>');
$('#rf').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target).entries());const btn=e.target.querySelector('button');btn.disabled=true;try{const r=await fetch('/api/report',{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify(f)}),j=await r.json();if(!r.ok)throw Error();openModal('Laporan Diterima','<p>Laporan tersimpan di Supabase dan menunggu verifikasi.</p><p>ID: <b>'+esc(j.report_id||'diterima')+'</b></p>')}catch{openModal('Laporan Gagal','<p>Laporan belum tersimpan. Periksa koneksi dan coba kembali.</p>')}}}
const content={map:['Peta Indonesia','<p>Peta publik menggunakan geografi nasional dari database dan dapat diperluas dengan filter wilayah, kategori, periode, dan sumber.</p><div class="mapbox"></div>'],data:['Data & Statistik','<p>Modul ini membaca dataset, indikator, periode, kualitas, dan sumber dari portal data.</p><div class="rankrow"><span>Dataset terdaftar</span><strong>'+fmt(portal?.tables?.data_sources?.length)+'</strong></div>'],monitor:['Pantau Perubahan','<p>Modul membaca early signals yang telah dipublikasikan. Sinyal tanpa data tidak dibuat-buat.</p><div class="rankrow"><span>Sinyal tersedia</span><strong>'+fmt(portal?.tables?.early_signals?.length)+'</strong></div>'],insights:['Wawasan & Intelligence','<p>Analisis berbasis claims, evidence, observations, dan sumber. Hasil hanya ditampilkan bila tersedia di sistem.</p>'],forecast:['Kemungkinan / Future Radar','<p>Forecast publik ditampilkan dengan horizon, model, confidence, faktor, dan ketidakpastian ketika data tersedia.</p><div class="rankrow"><span>Forecast tersedia</span><strong>'+fmt(portal?.tables?.forecasts?.length)+'</strong></div>'],solutions:['Solusi','<p>Solusi publik berasal dari tabel solusi dan dapat memuat tipe, dampak, risiko, kelayakan, asumsi, serta outcome.</p><div class="rankrow"><span>Solusi tersedia</span><strong>'+fmt(portal?.tables?.solutions?.length)+'</strong></div>'],about:['Tentang Nuansa Kita','<p>NUANSA KITA — ASPIRASI PUBLIK INDONESIA adalah portal untuk melihat masalah, mendengar suara warga, memahami data, memantau perubahan, mengantisipasi kemungkinan, dan mencari solusi secara transparan.</p>']};
function show(k){const v=content[k]||content.about;openModal(v[0],v[1])}
const actions={map:()=>show('map'),data:()=>show('data'),report,monitor:()=>show('monitor'),insights:()=>show('insights'),forecast:()=>show('forecast'),solutions:()=>show('solutions'),about:()=>show('about')};
$$('[data-act]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();actions[el.dataset.act]?.()}));
$$('.group>button').forEach(btn=>btn.addEventListener('click',()=>btn.parentElement.classList.toggle('open')));
$$('.group .sub a').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const t=a.textContent.trim();const map={'Terkini':'monitor','Berdasarkan Wilayah':'map','Berdasarkan Kategori':'data','Mendesak':'monitor','Belum Terselesaikan':'monitor','Sumber Data':'data','Kumpulan Data':'data','Indikator':'data','Kualitas & Pembaruan Data':'data','Laporkan Masalah':'report','Cerita Warga':'report','Keluhan':'report','Usulan':'report','Polling':'report','Diskusi':'report','Masalah Baru':'monitor','Meningkat':'monitor','Menurun':'monitor','Ramai Dibicarakan':'monitor','Peringatan':'monitor','Pola':'insights','Penyebab':'insights','Tren':'insights','Hubungan':'insights','Ringkasan Wilayah':'insights','Perkiraan':'forecast','Perbandingan':'forecast','Skenario':'forecast','Solusi Warga':'solutions','Solusi Pemerintah':'solutions','Praktik Baik':'solutions','Evaluasi Hasil':'solutions'};actions[map[t]]?.()}));
$$('.cat').forEach(b=>b.addEventListener('click',()=>show('data')));
$('#searchForm')?.addEventListener('submit',e=>{e.preventDefault();const q=$('#q').value.trim();if(q)search(q)});
$$('.map-switch button').forEach(b=>b.addEventListener('click',()=>{$$('.map-switch button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const box=$('.mapbox');if(box)box.style.filter=b.textContent.trim()==='Satelit'?'saturate(.65) brightness(.9)':'none'}));
if(sb){sb.auth.onAuthStateChange((_event,s)=>{session=s||null;renderAuth();});}
loadPortal();
})();