(()=>{'use strict';
const SUPABASE_URL='https://gfggmkeucgqkkyvummpu.supabase.co',SUPABASE_KEY='sb_publishable_ptCVbq9h15prKhT0OO5Zmg_LkE3cbw0';
const loadScript=(src,check)=>{if(check&&check())return Promise.resolve();return new Promise((resolve,reject)=>{const old=document.querySelector('script[data-nk-loader="'+src+'"]');if(old){old.addEventListener('load',()=>resolve(),{once:true});old.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src=src;s.async=true;s.dataset.nkLoader=src;s.onload=()=>resolve();s.onerror=reject;document.head.appendChild(s)})};
const ensureSupabase=()=>loadScript('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2',()=>!!window.supabase?.createClient);
const ensureLeaflet=()=>loadScript('https://unpkg.com/leaflet@1.9.4/dist/leaflet.js',()=>!!window.L);
async function isAdminSession(){try{await ensureSupabase();const c=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});const s=(await c.auth.getSession()).data?.session;if(!s?.access_token)return false;const r=await c.rpc('ad_admin_dashboard');return !r.error&&r.data?.is_admin===true}catch(e){console.warn('[admin-check]',e);return false}}
async function forceAdminRedirect(){try{if(location.pathname==='/admin.html'||location.search.includes('admin_preview'))return false;if(await isAdminSession()){location.replace('/admin.html');return true}}catch(e){console.warn('[admin-redirect]',e)}return false}
async function rescueLogin(){try{await ensureSupabase();const c=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});const box=document.querySelector('#modal'),body=document.querySelector('#mb');if(!box||!body)return;body.innerHTML='<h2>Login / Masuk</h2><form id="rescueLoginForm" class="authForm"><input name="email" type="email" required placeholder="Email"><input name="password" type="password" required minlength="6" placeholder="Kata Sandi"><button class="cta" type="submit">Login / Masuk</button><p id="rescueLoginMsg" class="authNote">Masuk untuk mengakses laporan dan fitur akun.</p></form>';box.classList.add('open');document.querySelector('#rescueLoginForm').onsubmit=async ev=>{ev.preventDefault();const f=Object.fromEntries(new FormData(ev.currentTarget)),m=document.querySelector('#rescueLoginMsg');m.textContent='Memproses login…';const r=await c.auth.signInWithPassword({email:f.email.trim(),password:f.password});if(r.error){m.textContent=r.error.message;return}sessionStorage.setItem('nk-login-ok','1');if(await isAdminSession()){location.replace('/admin.html');return}location.reload()}}catch(e){alert('Login gagal dimuat: '+(e.message||e))}}
async function runSubmenu(label){const t=String(label||'').trim();for(let i=0;i<12;i++){if(typeof window.NK_INTERACTIONS?.handleSubmenu==='function'){window.NK_INTERACTIONS.handleSubmenu(t);return true}await new Promise(r=>setTimeout(r,150))}const problemMenu=['Terkini','Berdasarkan Wilayah','Berdasarkan Kategori','Berdasarkan Status'];if(problemMenu.includes(t)){location.hash='masalah';return true}const regionMenu=['Ringkasan Indonesia','Provinsi','Kabupaten/Kota','Kecamatan','Desa/Kelurahan','Dusun','Pulau & Kawasan','Wilayah Prioritas'];if(regionMenu.includes(t)){location.hash='beranda';return true}return false}
const boot=()=>{if(window.__nkInteractionRescue)return;window.__nkInteractionRescue=true;document.addEventListener('click',async e=>{const auth=e.target.closest('#authBtn,.authBtn');if(auth){e.preventDefault();e.stopImmediatePropagation();try{await ensureSupabase();if(window.NK_INTERACTIONS?.authPanel){await window.NK_INTERACTIONS.authPanel()}else await rescueLogin()}catch(err){await rescueLogin()}return}const navBtn=e.target.closest('.nav .group>button');if(navBtn){e.preventDefault();e.stopImmediatePropagation();const g=navBtn.closest('.group');document.querySelectorAll('.nav .group').forEach(x=>{if(x!==g)x.classList.remove('open')});g?.classList.toggle('open');return}const sub=e.target.closest('.nav .group .sub a');if(sub){e.preventDefault();e.stopImmediatePropagation();const label=sub.dataset.submenu||sub.textContent.trim();try{await runSubmenu(label)}catch(err){console.warn('[submenu-rescue]',err)}return}const act=e.target.closest('[data-act]');if(act&&window.NK_INTERACTIONS?.actions){const fn=window.NK_INTERACTIONS.actions[act.dataset.act];if(typeof fn==='function'){e.preventDefault();e.stopImmediatePropagation();fn();return}}},true);window.addEventListener('error',err=>{console.warn('Indonesia Punya Masalah interaction rescue:',err.message);document.documentElement.classList.add('nk-js-error')});ensureSupabase().catch(()=>{});setTimeout(()=>forceAdminRedirect(),120);window.addEventListener('load',()=>setTimeout(()=>forceAdminRedirect(),180));setTimeout(()=>ensureLeaflet().catch(()=>{}),2200)};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();