(()=>{const $=(s,r=document)=>r.querySelector(s);const root=document.createElement('section');root.className='public-upgrade w';root.id='intelligence-core';root.innerHTML=`
<div class="pu-head"><div><h2>Intelligence Core — Data sampai Solusi</h2><p>Semua kemampuan dari blueprint lama dipasang sebagai modul publik yang dapat ditelusuri.</p></div><span class="pu-badge">PUBLIC • TRANSPARAN • BERBASIS SUMBER</span></div>
<div class="pu-hero pu-card"><img src="/assets/hero-reference.svg" alt="Ilustrasi visual referensi portal Indonesia Punya Masalah"><div class="pu-copy"><h3>Empat pertanyaan inti</h3><div class="pu-flow"><div class="pu-step">WHY<br><small>Mengapa?</small></div><div class="pu-step">NOW<br><small>Apa terjadi?</small></div><div class="pu-step">THEN<br><small>Apa mungkin?</small></div><div class="pu-step">ACTION<br><small>Apa dilakukan?</small></div><div class="pu-step">DATA<br><small>Sumber</small></div><div class="pu-step">EVIDENCE<br><small>Bukti</small></div><div class="pu-step">OUTCOME<br><small>Hasil</small></div><div class="pu-step">LEARN<br><small>Belajar</small></div></div></div></div>
<div class="pu-grid">
<div class="pu-card"><div class="pu-icon">◉</div><h3>Data Ocean</h3><p>Data resmi, geospasial, lingkungan, ekonomi, informasi publik, dan sinyal manusia.</p></div>
<div class="pu-card"><div class="pu-icon">✓</div><h3>Evidence Engine</h3><p>Setiap klaim dapat diberi status belum terverifikasi, bukti pendukung, kuat, atau konflik.</p></div>
<div class="pu-card"><div class="pu-icon">⌖</div><h3>Local Intelligence</h3><p>Profil wilayah dari Indonesia sampai desa/kelurahan dan area mikro saat data tersedia.</p></div>
<div class="pu-card"><div class="pu-icon">♟</div><h3>Human Voice</h3><p>Laporan warga, foto, video, cerita, survei, dan observasi dipisahkan dari fakta resmi.</p></div>
<div class="pu-card"><div class="pu-icon">◇</div><h3>Problem DNA</h3><p>Lokasi → waktu → sejarah → penyebab → dampak → pihak terdampak → solusi → hasil.</p></div>
<div class="pu-card"><div class="pu-icon">◎</div><h3>Knowledge Graph</h3><p>Hubungan masalah membantu membaca rantai dampak, bukan hanya satu angka.</p></div>
<div class="pu-card"><div class="pu-icon">↗</div><h3>Early Signal</h3><p>Perubahan kecil lintas sumber dipantau sebagai sinyal, bukan langsung dianggap fakta.</p></div>
<div class="pu-card"><div class="pu-icon">♢</div><h3>Future Radar</h3><p>Horizon 7/30/90 hari dan 1 tahun dengan asumsi, ketidakpastian, dan evaluasi.</p></div>
</div>
<div class="pu-wide">
<div class="pu-card pu-visual"><img src="/assets/quote-reference.svg" alt="Visual referensi data dan solusi"><div class="pu-copy"><h3>Alur kecerdasan publik</h3><p>Lihat masalah → Dengarkan manusia → Buktikan → Pahami → Antisipasi → Bertindak → Ukur → Belajar.</p><div class="pu-actions"><a class="pu-primary" href="#peta">Buka Peta Indonesia →</a><button class="pu-secondary" data-act="report">＋ Laporkan Masalah</button></div></div></div>
<div class="pu-card pu-map"><img src="/assets/map-reference.svg" alt="Ilustrasi peta Indonesia dengan legenda tingkat masalah"><div class="pu-copy"><h3>Peta &amp; Geography</h3><p>Wilayah nasional, kategori, sinyal, perubahan, dan sumber ditampilkan dengan status data.</p></div></div>
</div>
<div class="pu-wide pu-data">
<div class="pu-card"><h3>Sumber &amp; provenance</h3><div class="pu-list" id="puSources"><div class="pu-source"><b>BMKG</b><span class="pu-status">terdaftar</span></div><div class="pu-source"><b>BPS</b><span class="pu-status">terdaftar</span></div><div class="pu-source"><b>BNPB / Satu Data</b><span class="pu-status">terdaftar</span></div><div class="pu-source"><b>BIG / Geospasial</b><span class="pu-status">terdaftar</span></div></div><div class="pu-note">Status “terdaftar” berarti sumber tersedia di katalog. Ini tidak otomatis berarti seluruh dataset sudah tersinkron real-time.</div></div>
<div class="pu-card"><h3>Data nasional aktif</h3><div class="pu-live"><div class="metric"><strong>38</strong><span>Provinsi</span></div><div class="metric"><strong>514</strong><span>Kab/Kota</span></div><div class="metric"><strong>7.282</strong><span>Kecamatan</span></div></div><div class="pu-live"><div class="metric"><strong>83.529</strong><span>Desa/Kelurahan</span></div><div class="metric"><strong>7</strong><span>pilar intelligence</span></div><div class="metric"><strong>∞</strong><span>evidence ledger</span></div></div></div>
</div>
<div class="pu-trust">
<div class="pu-card"><div class="pu-icon">✓</div><div><h3>Transparansi</h3><p>Source, waktu, kualitas, confidence, uncertainty, dan provenance dipertahankan.</p></div></div>
<div class="pu-card"><div class="pu-icon">!</div><div><h3>Forecast bukan kepastian</h3><p>Perkiraan publik wajib menunjukkan asumsi, horizon, ketidakpastian, dan evaluasi.</p></div></div>
<div class="pu-card"><div class="pu-icon">◌</div><div><h3>Privacy by design</h3><p>Data pribadi sensitif tetap terbatas; sinyal sosial tidak diperlakukan sebagai kebenaran mutlak.</p></div></div>
</div>`;const anchor=$('footer'); if(anchor) anchor.parentNode.insertBefore(root,anchor); else document.body.appendChild(root);
async function load(){try{const r=await fetch('/api/data-sources');if(r.ok){const d=await r.json();const arr=d.sources||d.data||[];if(arr.length){const el=$('#puSources');el.innerHTML=arr.slice(0,8).map(x=>'<div class="pu-source"><b>'+String(x.name||x.source_name||'Sumber').replace(/</g,'&lt;')+'</b><span class="pu-status">'+String(x.status||x.sync_status||'terdaftar').replace(/</g,'&lt;')+'</span></div>').join('')}}}catch(e){}}load();})();