(()=>{
const SB_URL='https://gfggmkeucgqkkyvummpu.supabase.co';
const SB_KEY='sb_publishable_ptCVbq9h15prKhT0OO5Zmg_LkE3cb0';
const esc2=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const $2=id=>document.getElementById(id);
async function sb(path,opts={}){
  const r=await fetch(`${SB_URL}${path}`,{...opts,headers:{apikey:SB_KEY,Authorization:`Bearer ${SB_KEY}`,'Content-Type':'application/json','Accept':'application/json',...(opts.headers||{})}});
  const t=await r.text(); let d=null; try{d=t?JSON.parse(t):null}catch{d=t}
  if(!r.ok) throw new Error(typeof d==='string'?d:(d?.message||d?.hint||`HTTP ${r.status}`));
  return d;
}
function pageFrame(k,title,desc,body){return `<div class="page suite-page"><div class="suite-kicker">${esc2(k)}</div><h2>${esc2(title)}</h2><p class="muted suite-desc">${esc2(desc)}</p>${body}</div>`}
function activate(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$2(id)?.classList.add('active');document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});if(window.lucide)window.lucide.createIcons()}
function linkViews(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>window.render?.(b.dataset.view));}
function cardStat(label,value,sub,icon='◉'){return `<div class="suite-kpi"><span class="suite-icon">${icon}</span><div><small>${label}</small><b>${value}</b><span>${sub}</span></div></div>`}
function statusBox(text,ok=true){return `<div class="suite-status ${ok?'ok':'warn'}">${ok?'●':'!'} ${esc2(text)}</div>`}
async function renderMonitoring(){
  const host=$2('monitoring');host.innerHTML=pageFrame('MONITORING','Pantau apa yang sedang berubah','Sinyal, masalah, risiko, dan peringatan disajikan sebagai bahan pemantauan; status tetap dibedakan dari fakta terverifikasi.',`<div class="suite-grid-4">${cardStat('EARLY SIGNAL','Live','sumber sinyal','◌')}${cardStat('PROBLEMS','Live','masalah terdeteksi','!')}${cardStat('REPORTS','Live','laporan warga','✎')}${cardStat('PREDICTIONS','Live','forecast aktif','⌁')}</div><div class="suite-grid-2"><div class="card suite-panel"><div class="suite-panel-head"><div><h3>Early Signals</h3><p>Perubahan yang layak dipantau lebih lanjut.</p></div><button class="btn-outline" id="mon-refresh">Refresh</button></div><div id="mon-signals" class="suite-list"><div class="loading">Memuat sinyal…</div></div></div><div class="card suite-panel"><div class="suite-panel-head"><div><h3>Masalah Prioritas</h3><p>Diurutkan berdasarkan dampak dan confidence.</p></div><button class="btn-primary" data-view="problems">Buka Masalah</button></div><div id="mon-problems" class="suite-list"><div class="loading">Memuat masalah…</div></div></div></div>`);
  activate('monitoring');linkViews();
  async function load(){
    const sig=$2('mon-signals'), prob=$2('mon-problems');
    try{const rows=await sb('/rest/v1/early_signals?select=id,title,category,detected_at,magnitude,confidence,status&order=detected_at.desc&limit=8');sig.innerHTML=rows?.length?rows.map(r=>`<div class="suite-row"><div><b>${esc2(r.title)}</b><small>${esc2(r.category||'Sinyal')} · ${r.detected_at?new Date(r.detected_at).toLocaleString('id-ID'):'—'}</small></div><span class="pill">confidence ${esc2(r.confidence??'—')}</span></div>`).join(''):statusBox('Belum ada early signal produksi.',false)}catch(e){sig.innerHTML=statusBox(`Sinyal belum tersedia: ${e.message}`,false)}
    try{const rows=await sb('/rest/v1/problems?select=id,title,category,status,confidence,impact_score,last_observed_at&order=impact_score.desc.nullslast,updated_at.desc&limit=8');prob.innerHTML=rows?.length?rows.map(r=>`<button class="suite-row suite-button" data-problem="${esc2(r.id)}"><div><b>${esc2(r.title)}</b><small>${esc2(r.category||'Masalah')} · ${esc2(r.status||'detected')}</small></div><span class="pill">impact ${esc2(r.impact_score??'—')}</span></button>`).join(''):statusBox('Belum ada masalah produksi.',false);prob.querySelectorAll('[data-problem]').forEach(b=>b.onclick=()=>window.render?.('problems'));}catch(e){prob.innerHTML=statusBox(`Problem Engine belum tersedia: ${e.message}`,false)}
  }
  $2('mon-refresh').onclick=load;await load();
}
async function renderIntelligence(){
 const host=$2('intelligence');host.innerHTML=pageFrame('INTELLIGENCE','Pahami pola di balik masalah','Ruang kerja analitik untuk evidence, pola, hubungan penyebab, tren, forecast, dan tingkat keyakinan.',`<div class="suite-grid-3">${cardStat('EVIDENCE','Traceable','sumber dapat ditelusuri','◎')}${cardStat('PATTERN','Active','pola perubahan','⌁')}${cardStat('CAUSAL','Linked','hubungan sebab','↗')}</div><div class="suite-grid-2"><div class="card suite-panel"><div class="suite-panel-head"><div><h3>Evidence Explorer</h3><p>Hubungkan laporan, observasi, sinyal, dan sumber.</p></div></div><div id="intel-evidence" class="suite-list"><div class="loading">Memuat evidence…</div></div></div><div class="card suite-panel"><div class="suite-panel-head"><div><h3>Forecast & Confidence</h3><p>Prediksi disertai horizon, probabilitas, dan confidence.</p></div><button class="btn-outline" data-view="solutions">Ke Solusi</button></div><div id="intel-pred" class="suite-list"><div class="loading">Memuat prediksi…</div></div></div></div><div class="card suite-panel"><h3>AI Brain Pipeline</h3><div class="pipeline"><span>Data Ocean</span><i>→</i><span>Validation</span><i>→</i><span>Problem Engine</span><i>→</i><span>Pattern</span><i>→</i><span>Causal</span><i>→</i><span>Forecast</span><i>→</i><span>Solution</span></div>${statusBox('AI tetap evidence-first: keluaran analitik tidak diperlakukan sebagai fakta tanpa dukungan bukti.')}</div>`);
 activate('intelligence');linkViews();
 try{const rows=await sb('/rest/v1/evidence_items?select=id,evidence_type,captured_at,trust_score,notes,source_id,report_id,observation_id,social_signal_id&order=created_at.desc&limit=8');$2('intel-evidence').innerHTML=rows?.length?rows.map(r=>`<div class="suite-row"><div><b>${esc2(r.evidence_type)}</b><small>${r.captured_at?new Date(r.captured_at).toLocaleString('id-ID'):'—'} · trust ${esc2(r.trust_score??'—')}</small></div><span class="pill">${r.source_id?'SOURCE':r.report_id?'REPORT':r.observation_id?'OBS':'SIGNAL'}</span></div>`).join(''):statusBox('Belum ada evidence yang dapat ditampilkan.',false)}catch(e){$2('intel-evidence').innerHTML=statusBox(`Evidence belum tersedia: ${e.message}`,false)}
 try{const rows=await sb('/rest/v1/predictions?select=id,target_type,horizon_days,probability,confidence,outcome_status,predicted_at&order=predicted_at.desc&limit=8');$2('intel-pred').innerHTML=rows?.length?rows.map(r=>`<div class="suite-row"><div><b>${esc2(r.target_type)}</b><small>${esc2(r.horizon_days)} hari · ${r.predicted_at?new Date(r.predicted_at).toLocaleString('id-ID'):'—'}</small></div><span class="pill">${r.probability==null?'—':(Number(r.probability)*100).toFixed(0)+'%'} · ${esc2(r.confidence??'—')}</span></div>`).join(''):statusBox('Belum ada prediksi produksi.',false)}catch(e){$2('intel-pred').innerHTML=statusBox(`Prediction Engine belum tersedia: ${e.message}`,false)}
}
function renderSolutions(){
 const host=$2('solutions');host.innerHTML=pageFrame('SOLUSI','Dari masalah menuju tindakan','Bandingkan pilihan solusi dengan konteks wilayah, evidence, dampak, risiko, biaya, dan hasil yang dapat diukur.',`<div class="suite-grid-3">${cardStat('OPTIONS','3','contoh opsi','◇')}${cardStat('RISK','Measured','risiko harus dicatat','⚠')}${cardStat('OUTCOME','Trackable','indikator hasil','✓')}</div><div class="card suite-panel"><div class="suite-panel-head"><div><h3>Solution Workspace</h3><p>Pilih masalah, bandingkan opsi, lalu catat keputusan dan indikator hasil.</p></div><button class="btn-primary" data-view="problems">Pilih Masalah</button></div><div class="solution-table"><div><b>Opsi</b><b>Dampak</b><b>Risiko</b><b>Biaya</b><b>Outcome</b></div><div><span>Perbaikan layanan dasar</span><span class="good">Tinggi</span><span>Sedang</span><span>Sedang</span><span>Terukur</span></div><div><span>Intervensi infrastruktur</span><span class="good">Tinggi</span><span>Sedang</span><span>Tinggi</span><span>Terukur</span></div><div><span>Program kolaborasi warga</span><span>Sedang</span><span>Rendah</span><span>Rendah</span><span>Terukur</span></div></div>${statusBox('Solusi bukan klaim otomatis: keputusan harus dikaitkan dengan evidence, konteks, dan outcome.')}</div>`);
 activate('solutions');linkViews();
}
async function renderFuture(){
 const host=$2('future');host.innerHTML=pageFrame('FUTURE RADAR','Melihat kemungkinan ke depan','Forecast tidak menjanjikan kepastian. Setiap prediksi membawa horizon, probabilitas, confidence, evidence, dan ketidakpastian.',`<div class="suite-grid-4">${cardStat('7 HARI','Short','perubahan cepat','◷')}${cardStat('30 HARI','Medium','tren bulanan','◴')}${cardStat('90 HARI','Longer','skenario','◵')}${cardStat('CONFIDENCE','Evidence','ukur keyakinan','◎')}</div><div class="card suite-panel"><div class="suite-panel-head"><div><h3>Future Radar</h3><p>Forecast yang tersedia dari database.</p></div><button class="btn-outline" id="future-refresh">Refresh</button></div><div id="future-list" class="suite-list"><div class="loading">Memuat forecast…</div></div></div>`);activate('future');linkViews();
 async function load(){try{const rows=await sb('/rest/v1/predictions?select=id,target_type,target_id,horizon_days,scenario,probability,confidence,outcome_status,predicted_at&order=predicted_at.desc&limit=20');$2('future-list').innerHTML=rows?.length?rows.map(r=>`<div class="suite-row"><div><b>${esc2(r.target_type)} · ${esc2(r.horizon_days)} hari</b><small>Predicted ${r.predicted_at?new Date(r.predicted_at).toLocaleString('id-ID'):'—'} · status ${esc2(r.outcome_status)}</small></div><span class="pill">prob ${r.probability==null?'—':(Number(r.probability)*100).toFixed(0)+'%'} · conf ${esc2(r.confidence??'—')}</span></div>`).join(''):statusBox('Belum ada forecast produksi.',false)}catch(e){$2('future-list').innerHTML=statusBox(`Forecast belum tersedia: ${e.message}`,false)}}
 $2('future-refresh').onclick=load;await load();
}
function renderControl(){
 const host=$2('control');host.innerHTML=pageFrame('CONTROL CENTER','Kesehatan sistem','Satu tempat untuk melihat status web, database, pipeline geometry, AI, keamanan, dan sinkronisasi.',`<div class="suite-grid-4">${cardStat('WEB','Online','frontend','◉')}${cardStat('DATABASE','Connected','Supabase','◆')}${cardStat('GEOMETRY','Running','BIG import','⌂')}${cardStat('AUDIT','Enabled','traceability','✓')}</div><div class="suite-grid-2"><div class="card suite-panel"><h3>Pipeline</h3><div class="health-list"><div>${statusBox('Region registry tersedia',true)}</div><div>${statusBox('Province geometry selesai',true)}</div><div>${statusBox('Regency geometry selesai',true)}</div><div>${statusBox('District geometry berjalan bertahap',true)}</div><div>${statusBox('Village geometry berjalan bertahap',true)}</div></div></div><div class="card suite-panel"><h3>Governance</h3><div class="health-list"><div>${statusBox('Evidence dipisahkan dari claim',true)}</div><div>${statusBox('Confidence dan uncertainty ditampilkan',true)}</div><div>${statusBox('Human review tetap diperlukan',true)}</div><div>${statusBox('Audit trail tersedia di schema',true)}</div></div></div></div>`);activate('control');linkViews();
}
function renderAccount(){const host=$2('account');host.innerHTML=pageFrame('AKUN','Ruang pengguna','Tempat kontribusi, aktivitas, preferensi, dan peran akses.',`<div class="card suite-panel"><div class="account-hero"><div class="avatar">IP</div><div><h3>Pengguna publik</h3><p class="muted">Belum login. Anda tetap dapat menjelajah data dan mengirim sinyal awal.</p></div></div><div class="suite-grid-3">${cardStat('ROLE','Guest','akses publik','○')}${cardStat('REPORTS','—','laporan tersimpan','✎')}${cardStat('SAVED','—','wilayah tersimpan','♡')}</div><div class="account-actions"><button class="btn-primary" data-view="report">Buat Laporan</button><button class="btn-outline" id="account-local">Lihat Laporan Perangkat</button></div><div id="account-local-list"></div></div>`);activate('account');linkViews();$2('account-local').onclick=()=>{const rows=JSON.parse(localStorage.getItem('ipm_reports')||'[]');$2('account-local-list').innerHTML=rows.length?`<div class="suite-list">${rows.slice(0,10).map(r=>`<div class="suite-row"><div><b>${esc2(r.title)}</b><small>${esc2(r.category)} · ${new Date(r.created_at).toLocaleString('id-ID')}</small></div><span class="pill">${esc2(r.status)}</span></div>`).join('')}</div>`:statusBox('Belum ada laporan tersimpan di perangkat.',false)};}
function renderMore(){const host=$2('more');host.innerHTML=pageFrame('LAINNYA','Metodologi & sumber','Tentang bagaimana Indonesia Punya Masalah menghubungkan data, manusia, evidence, pola, dan keputusan.',`<div class="suite-grid-2"><div class="card suite-panel"><h3>Prinsip Platform</h3><div class="principles"><p><b>01</b> Lihat masalah</p><p><b>02</b> Dengarkan manusia</p><p><b>03</b> Kumpulkan dan validasi data</p><p><b>04</b> Pahami penyebab dan pola</p><p><b>05</b> Prediksi kemungkinan</p><p><b>06</b> Cari solusi dan ukur hasil</p></div></div><div class="card suite-panel"><h3>Sumber & Integritas</h3><p class="muted">Sumber wilayah utama terintegrasi dengan registry BIG. Evidence, provenance, confidence, uncertainty, dan audit log menjadi bagian dari arsitektur data.</p>${statusBox('Jangan menampilkan sesuatu sebagai fakta tanpa sumber/evidence yang mendukung.',true)}</div></div>`);activate('more');linkViews();}
const originalRender=window.render;
window.render=async function(view,extra=''){
 if(view==='monitoring')return renderMonitoring();
 if(view==='intelligence')return renderIntelligence();
 if(view==='future')return renderFuture();
 if(view==='solutions')return renderSolutions();
 if(view==='control')return renderControl();
 if(view==='account')return renderAccount();
 if(view==='more')return renderMore();
 return originalRender?originalRender(view,extra):activate(view);
};
window.addEventListener('DOMContentLoaded',()=>{linkViews();if(window.lucide)window.lucide.createIcons()});
})();
