const SUPABASE_URL='https://gfggmkeucgqkkyvummpu.supabase.co';
const SUPABASE_KEY='sb_publishable_ptCVbq9h15prKhT0OO5Zmg_LkE3cb0';
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>new Intl.NumberFormat('id-ID').format(Number(n)||0); const cache=new Map();
async function supabase(path,opts={}){const r=await fetch(`${SUPABASE_URL}${path}`,{...opts,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json','Accept':'application/json',...(opts.headers||{})}});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Error(typeof d==='string'?d:(d?.message||d?.hint||`HTTP ${r.status}`));return d}
async function regions(level,parent='',limit=100){const k=`${level}|${parent}|${limit}`;if(cache.has(k))return cache.get(k);let u=`/rest/v1/regions?select=id,name,level,admin_code_bps,admin_code_pum,parent_region_id,boundary_status,source_name&source_name=eq.BIG&level=eq.${encodeURIComponent(level)}&order=name.asc&limit=${limit}`;if(parent)u+=`&parent_region_id=eq.${encodeURIComponent(parent)}`;const p=supabase(u);cache.set(k,p);return p}
const pageData={
regions:['JELAJAHI INDONESIA','Dari Indonesia sampai dusun','Navigasi wilayah resmi secara bertingkat, dengan boundary dan parent-child relation.'],
problems:['MASALAH','Masalah yang perlu perhatian','Pisahkan masalah, sinyal, laporan warga, evidence, status verifikasi, dan dampak.'],
data:['DATA & STATISTIK','Data Indonesia dalam satu tempat','Lihat cakupan wilayah, kualitas, sumber, waktu observasi, dan status data.'],
report:['SUARA WARGA','Ceritakan masalah di sekitar Anda','Cerita warga menjadi sinyal yang harus diverifikasi sebelum dipakai sebagai fakta produksi.'],
monitoring:['MONITORING','Apa yang sedang berubah?','Pantau masalah baru, membesar, menurun, viral, dan early warning.'],
intelligence:['INTELLIGENCE','Memahami pola di balik masalah','Pattern, causal, trend, signal, forecast, dan AI bekerja dengan evidence-first.'],
future:['FUTURE RADAR','Melihat kemungkinan ke depan','Forecast ditampilkan bersama horizon, probabilitas, confidence, evidence, dan ketidakpastian.'],
solutions:['SOLUSI','Dari masalah menuju tindakan','Bandingkan opsi berdasarkan kecocokan wilayah, bukti, dampak, risiko, dan outcome.'],
control:['CONTROL CENTER','Kesehatan sistem','Pantau web publik, pipeline data, geometry, AI, security, dan sinkronisasi.'],
account:['AKUN','Ruang pengguna','Akses, kontribusi, dan peran akan mengikuti akun dan izin.'],
more:['LAINNYA','Lebih banyak cara ikut terlibat','Pelajari metodologi, sumber data, tentang platform, dan kebijakan.']};
function shell(k,body){const p=pageData[k];return `<div class="page"><span class="eyebrow">${p[0]}</span><h2>${p[1]}</h2><p class="muted">${p[2]}</p>${body}</div>`}
function setActive(view){document.querySelectorAll('.view').forEach(e=>e.classList.remove('active'));const el=$(view);if(el)el.classList.add('active');document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
function bindViews(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const v=b.dataset.view; if(v)render(v)});}
function render(v){if(v==='home'){setActive('home');bindViews();return}if(v==='regions')return renderRegions();if(v==='problems')return renderProblems();if(v==='data')return renderData();if(v==='report')return renderReport();if(v==='monitoring')return renderMonitoring();if(v==='intelligence')return renderIntelligence();if(v==='future')return renderFuture();if(v==='solutions')return renderSolutions();if(v==='control')return renderControl();if(v==='account')return renderAccount();if(v==='more')return renderMore();if(v==='map')return renderMap();if(v==='result')return setActive('result');}
function pageInto(id,html){$(id).innerHTML=html;setActive(id);bindViews()}
async function renderRegions(){pageInto('regions',shell('regions',`<div class="card"><div class="cardhead"><b>PROVINSI</b><span id="region-status">memuat…</span></div><div id="region-list" class="regionlist"></div></div><div class="card"><div class="cardhead"><b>DRILL-DOWN</b><span>Provinsi → Kab/Kota → Kecamatan → Desa/Kelurahan</span></div><div id="region-detail" class="muted">Pilih provinsi untuk membuka tingkat berikutnya.</div></div>`));const list=$('region-list');try{const rows=await regions('province','',38);list.innerHTML=rows.map(r=>`<button class="regionrow" data-id="${esc(r.id)}"><span><b>${esc(r.name)}</b><small>${esc(r.admin_code_pum||r.admin_code_bps||'')}</small></span><span>${r.boundary_status==='loaded'?'BOUNDARY OK':'BOUNDARY PENDING'} →</span></button>`).join('');$('region-status').textContent=`${fmt(rows.length)} provinsi`;list.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>drill(b.dataset.id,b.querySelector('b').textContent,'city'));}catch(e){list.innerHTML=`<div class="empty"><b>Data wilayah belum dapat dimuat.</b><small>${esc(e.message)}</small></div>`;$('region-status').textContent='fallback'}}
async function drill(parentId,name,next){const d=$('region-detail');d.innerHTML=`<div class="loading">Membuka ${esc(name)}…</div>`;const label={city:'Kabupaten/Kota',district:'Kecamatan',village:'Desa/Kelurahan'}[next];try{const rows=await regions(next,parentId,100);d.innerHTML=`<div class="subcrumb"><b>${esc(name)}</b> → ${label}</div><div class="regionlist compact">${rows.map(r=>`<button class="regionrow" data-id="${esc(r.id)}" data-level="${esc(r.level)}"><span><b>${esc(r.name)}</b><small>${esc(r.admin_code_pum||r.admin_code_bps||'')}</small></span><span>${r.boundary_status==='loaded'?'OK':'PENDING'} →</span></button>`).join('')||'<div class="empty">Belum ada child region.</div>'}</div>`;d.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{const n=b.dataset.level==='city'?'district':b.dataset.level==='district'?'village':null;if(n)drill(b.dataset.id,b.querySelector('b').textContent,n)});}catch(e){d.innerHTML=`<div class="empty"><b>Drill-down gagal.</b><small>${esc(e.message)}</small></div>`}}
function renderMap(){pageInto('map',shell('regions',`<div class="card"><div class="cardhead"><div><b>PETA INDONESIA</b><p class="muted">Peta publik akan menggunakan boundary PostGIS yang tersimpan di wilayah BIG.</p></div><button class="btn-primary" data-view="regions">Jelajahi wilayah</button></div><div class="map big"><div class="mapgrid"></div><div class="island a"></div><div class="island b"></div><div class="island c"></div><div class="island d"></div><i class="pin p1">●</i><i class="pin p2">●</i><i class="pin p3">●</i></div><div class="notice success">Geometry engine terhubung bertahap. Peta produksi akan menampilkan status boundary per wilayah.</div></div>`))}
function renderProblems(){pageInto('problems',shell('problems',`<div class="kpirow"><div class="kpi"><small>PROBLEM ENGINE</small><b>READY</b><span>menunggu evidence produksi</span></div><div class="kpi"><small>HUMAN SIGNAL</small><b>ON</b><span>laporan dipisahkan dari fakta</span></div><div class="kpi"><small>TRACEABILITY</small><b>100%</b><span>target setiap claim punya sumber</span></div></div><div class="list"><article><mark>NEW</mark><div><b>Masalah baru</b><small>Masuk dari observasi, laporan warga, dan sumber publik.</small></div></article><article><mark>VERIFY</mark><div><b>Verifikasi masalah</b><small>Gabungkan bukti sebelum menetapkan status dan dampak.</small></div></article><article><mark>TRACK</mark><div><b>Pantau perubahan</b><small>Bandingkan baseline, tren, dan sinyal awal.</small></div></article></div>`))}
function renderData(){pageInto('data',shell('data',`<div class="stats"><div><small>PROVINSI</small><b>38</b><span>inventaris BIG</span></div><div><small>KAB/KOTA</small><b>514</b><span>inventaris BIG</span></div><div><small>KECAMATAN</small><b>7.282</b><span>geometry runner</span></div><div><small>DESA/KEL</small><b>83.529</b><span>geometry runner</span></div></div><div class="grid2"><div class="card"><div class="cardhead"><b>DATA TRUST</b><b>91*</b></div><div class="meter"><i style="width:91%"></i></div><p class="muted">Freshness • completeness • consistency • provenance.</p></div><div class="card"><b>PIPELINE</b><div class="pipeline"><span>Acquisition</span><span>Validation</span><span>Geo Engine</span><span>Knowledge Graph</span><span>Problem Engine</span><span>AI Brain</span></div></div></div>`))}
function renderReport(){pageInto('report',shell('report',`<div class="form card"><label>Judul masalah<input id="r-title" placeholder="Contoh: Jalan rusak di depan sekolah"></label><label>Lokasi<input id="r-location" placeholder="Desa / Kecamatan / Kabupaten"></label><label>Kategori<select id="r-category"><option>Infrastruktur</option><option>Ekonomi</option><option>Pendidikan</option><option>Kesehatan</option><option>Lingkungan</option><option>Sosial</option></select></label><label>Kejadian<input id="r-date" type="date"></label><label>Ceritakan<textarea id="r-story" rows="7" placeholder="Apa yang terjadi? Siapa yang terdampak? Sejak kapan?"></textarea></label><div class="notice">Laporan warga adalah sinyal awal. Sistem tidak otomatis menganggapnya sebagai fakta.</div><button id="send-report" class="btn-primary">Kirim laporan</button><div id="report-result"></div></div>`));$('send-report').onclick=async()=>{const x={title:$('r-title').value.trim(),location:$('r-location').value.trim(),category:$('r-category').value,narrative:$('r-story').value.trim(),occurred_at:$('r-date').value||null};if(!x.title||!x.narrative){$('report-result').innerHTML='<div class="notice danger">Judul dan cerita wajib diisi.</div>';return}$('report-result').innerHTML='<div class="notice">Menyiapkan laporan…</div>';try{await supabase('/rest/v1/human_reports',{method:'POST',body:JSON.stringify({category:x.category,title:x.title,narrative:`${x.location?`Lokasi: ${x.location}\n`:''}${x.narrative}`,occurred_at:x.occurred_at,verification_status:'received'})});$('report-result').innerHTML='<div class="notice success">Laporan sudah diterima sebagai sinyal warga. Verifikasi tetap diperlukan.</div>'}catch(e){$('report-result').innerHTML=`<div class="notice danger">Belum bisa dikirim dari halaman publik. ${esc(e.message)}</div>`}}
function renderMonitoring(){pageInto('monitoring',shell('monitoring',`<div class="grid2"><div class="card"><small>EARLY WARNING</small><h3>Perubahan yang perlu dilihat</h3><div class="empty"><b>Menunggu stream production signals</b><small>Trend engine akan mengisi berdasarkan observation dan social signal yang tervalidasi.</small></div></div><div class="card"><small>SUARA WARGA</small><h3>Jangan abaikan sinyal kecil</h3><p class="muted">Platform menempatkan laporan manusia sebagai bahan penting untuk menemukan masalah yang belum terlihat di dataset formal.</p><button class="btn-primary" data-view="report">Ceritakan masalah</button></div></div>`))}
function renderIntelligence(){pageInto('intelligence',shell('intelligence',`<div class="ai"><article><b>Pattern AI</b><span>Temukan pola berulang.</span></article><article><b>Causal Analysis</b><span>Uji hipotesis penyebab.</span></article><article><b>Trend & Signal</b><span>Deteksi perubahan.</span></article><article><b>Future Radar</b><span>Susun kemungkinan.</span></article><article><b>Forecast Engine</b><span>Hitung probabilitas.</span></article><article><b>AI Brain</b><span>Belajar dari outcome.</span></article></div><div class="card"><b>PRINSIP UTAMA</b><p class="muted">Tidak ada klaim penting tanpa sumber. Tidak ada prediksi tanpa baseline. Tidak ada rekomendasi tanpa memahami konteks manusia.</p></div>`))}
function renderFuture(){pageInto('future',shell('future',`<div class="forecast"><article><small>SCENARIO A</small><strong>—</strong><b>Baseline belum tersedia</b><span>Perlu data historis.</span></article><article><small>SCENARIO B</small><strong>—</strong><b>Stabil</b><span>Belum dihitung.</span></article><article><small>SCENARIO C</small><strong>—</strong><b>Berubah</b><span>Belum dihitung.</span></article></div><div class="card"><b>FORECAST SAFETY GATE</b><p class="muted">Forecast akan selalu memisahkan fakta, asumsi, probabilitas, dan ketidakpastian.</p></div>`))}
function renderSolutions(){pageInto('solutions',shell('solutions',`<div class="list"><article><b>01</b><div><b>Solusi berbasis wilayah</b><small>Fokus pada akar dan kondisi lokal.</small></div><span>BEST FIT</span></article><article><b>02</b><div><b>Kolaborasi warga & pemerintah</b><small>Report → validasi → tindakan → outcome.</small></div><span>TRACK</span></article><article><b>03</b><div><b>Uji skenario</b><small>Simulasikan dampak sebelum intervensi.</small></div><span>SIMULATE</span></article></div>`))}
function renderControl(){pageInto('control',shell('control',`<div class="control"><div><small>PUBLIC WEB</small><b>ONLINE</b><span>Human-centered shell</span></div><div><small>GEOMETRY</small><b>RUNNING</b><span>District + village</span></div><div><small>DATA</small><b>TRACEABLE</b><span>Source-aware</span></div><div><small>AI</small><b>GUARDED</b><span>Evidence first</span></div></div>`))}
function renderAccount(){pageInto('account',shell('account',`<div class="form card"><label>Nama<input placeholder="Nama tampilan"></label><label>Peran<select><option>Warga</option><option>Peneliti</option><option>Pemerintah</option><option>Moderator</option></select></label><button class="btn-primary">Simpan</button></div>`))}
function renderMore(){pageInto('more',shell('more',`<div class="list"><article><b>Tentang platform</b><small>Fokus pada masalah nyata dan dampaknya bagi manusia.</small></article><article><b>Sumber & metodologi</b><small>Setiap data produksi seharusnya memiliki provenance, waktu, dan quality score.</small></article><article><b>Transparansi AI</b><small>Probability bukan kepastian; rekomendasi dapat berubah ketika evidence bertambah.</small></article></div>`))}
async function analyze(){const q=$('question').value.trim();if(!q)return;pageInto('result',`<div class="page"><span class="eyebrow">PENCARIAN & ANALISIS</span><h2>“${esc(q)}”</h2><div id="analysis-body" class="card"><div class="loading"><b>Mencari evidence…</b><small>Menghubungkan pertanyaan dengan data, wilayah, dan sumber yang tersedia.</small></div></div></div>`);try{const r=await fetch(`/api/ask?q=${encodeURIComponent(q)}`);if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();$('analysis-body').innerHTML=`<div class="card"><b>${esc(d.summary||'Analisis selesai')}</b><p class="muted">Confidence: ${esc(d.confidence??'—')}</p><p class="muted">${esc(d.evidence_strength||'Evidence layer sedang diproses.')}</p></div>`}catch(e){$('analysis-body').innerHTML=`<div class="notice danger"><b>Analisis produksi belum tersedia.</b><small>${esc(e.message)}</small></div>`}}
$('ask').onclick=analyze;$('question').addEventListener('keydown',e=>{if(e.key==='Enter')analyze()});document.querySelectorAll('.topic-chips button').forEach(b=>b.onclick=()=>{$('question').value=b.dataset.q;analyze()});$('mobileMenu').onclick=()=>{$('mainNav').classList.toggle('open')};bindViews();setActive('home');
