const SUPABASE_URL='https://gfggmkeucgqkkyvummpu.supabase.co';
const SUPABASE_KEY='sb_publishable_ptCVbq9h15prKhT0OO5Zmg_LkE3cb0';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>new Intl.NumberFormat('id-ID').format(Number(n)||0);
const cache=new Map();

async function supabase(path,opts={}){
  const r=await fetch(`${SUPABASE_URL}${path}`,{...opts,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json','Accept':'application/json',...(opts.headers||{})}});
  const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}
  if(!r.ok)throw new Error(typeof d==='string'?d:(d?.message||d?.hint||`HTTP ${r.status}`));
  return d;
}

async function regions(level,parent='',limit=100,search=''){
  const key=`${level}|${parent}|${limit}|${search}`;
  if(cache.has(key))return cache.get(key);
  let u=`/rest/v1/regions?select=id,name,official_name,level,admin_code_bps,admin_code_pum,parent_region_id,boundary_status,source_name,latitude,longitude&source_name=eq.BIG&level=eq.${encodeURIComponent(level)}&order=name.asc&limit=${limit}`;
  if(parent)u+=`&parent_region_id=eq.${encodeURIComponent(parent)}`;
  if(search)u+=`&name=ilike.*${encodeURIComponent(search)}*`;
  const p=supabase(u);cache.set(key,p);return p;
}

const pageData={
 regions:['JELAJAHI INDONESIA','Dari Indonesia sampai dusun','Navigasi wilayah resmi dari provinsi sampai desa/kelurahan dengan hubungan parent-child.'],
 problems:['MASALAH','Masalah yang perlu perhatian','Daftar masalah, status, dampak, confidence, dan perubahan yang tersedia di basis data.'],
 data:['DATA & STATISTIK','Data Indonesia dalam satu tempat','Lihat cakupan wilayah, kualitas data, boundary, sumber, dan pipeline.'],
 report:['SUARA WARGA','Ceritakan masalah di sekitar Anda','Kirim laporan warga untuk menjadi sinyal awal yang dapat diverifikasi.'],
 monitoring:['MONITORING','Apa yang sedang berubah?','Pantau masalah baru, tren, risiko, dan peringatan.'],
 intelligence:['INTELLIGENCE','Memahami pola di balik masalah','Gabungkan evidence, pattern, causal, trend, dan forecast untuk memahami masalah.'],
 solutions:['SOLUSI','Dari masalah menuju tindakan','Bandingkan opsi, risiko, dampak, dan tindak lanjut berbasis evidence.'],
 account:['AKUN','Ruang pengguna','Akses kontribusi dan pengaturan akun.'],
 more:['LAINNYA','Tentang platform','Metodologi, sumber, kebijakan, dan dokumentasi.']
};

function shell(k,body){const p=pageData[k]||pageData.more;return `<div class="page"><span class="eyebrow">${p[0]}</span><h2>${p[1]}</h2><p class="muted">${p[2]}</p>${body}</div>`}
function setActive(view){document.querySelectorAll('.view').forEach(e=>e.classList.remove('active'));const el=$(view);if(el)el.classList.add('active');document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'});}
function bindViews(){document.querySelectorAll('[data-view]').forEach(b=>{b.onclick=()=>render(b.dataset.view)});}
function pageInto(id,html){$(id).innerHTML=html;setActive(id);bindViews();if(window.lucide)window.lucide.createIcons();}

async function renderRegions(){
 pageInto('regions',shell('regions',`<div class="pathbar" id="region-path">Indonesia / Provinsi</div><div class="region-layout"><div class="card"><div class="cardhead"><b>DAFTAR WILAYAH</b><span id="region-status">memuat…</span></div><div class="search-wrap small"><span>⌕</span><input id="region-search" placeholder="Cari provinsi atau wilayah…"><button id="region-search-btn">Cari</button></div><div id="region-list" class="regionlist"></div></div><div class="card"><div class="cardhead"><b>RINGKASAN WILAYAH</b><span>hierarki resmi</span></div><div id="region-detail" class="muted">Pilih wilayah di sebelah kiri untuk membuka tingkat berikutnya.</div></div></div>`));
 const list=$('region-list'),status=$('region-status');
 async function load(){list.innerHTML='<div class="loading"><b>Memuat wilayah…</b><small>Mengambil registry BIG.</small></div>';try{const rows=await regions('province','',38,$('region-search').value.trim());list.innerHTML=rows.map(r=>`<button class="regionrow" data-id="${esc(r.id)}"><span><b>${esc(r.name)}</b><small>${esc(r.admin_code_pum||r.admin_code_bps||'')}</small></span><span>${r.boundary_status==='loaded'?'BOUNDARY OK':'BOUNDARY PENDING'} →</span></button>`).join('')||'<div class="empty">Tidak ada wilayah.</div>';status.textContent=`${fmt(rows.length)} provinsi`;list.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>drill(b.dataset.id,b.querySelector('b').textContent,'city'));}catch(e){status.textContent='mode aman';list.innerHTML=`<div class="empty"><b>Data wilayah belum dapat dimuat.</b><small>${esc(e.message)}</small></div>`}}
 $('region-search-btn').onclick=load;$('region-search').onkeydown=e=>{if(e.key==='Enter')load()};await load();
}
async function drill(parentId,name,next){const d=$('region-detail');if(!d)return;const labels={city:'Kabupaten / Kota',district:'Kecamatan',village:'Desa / Kelurahan'};d.innerHTML=`<div class="loading"><b>Membuka ${esc(name)}…</b><small>Mengambil ${labels[next]}.</small></div>`;try{const rows=await regions(next,parentId,200);$('region-path').textContent=`Indonesia / ${name} / ${labels[next]}`;d.innerHTML=`<div class="subcrumb"><b>${esc(name)}</b><span>→ ${labels[next]}</span></div><div class="regionlist compact">${rows.map(r=>`<button class="regionrow" data-id="${esc(r.id)}" data-level="${esc(r.level)}"><span><b>${esc(r.name)}</b><small>${esc(r.admin_code_pum||r.admin_code_bps||'')}</small></span><span>${r.boundary_status==='loaded'?'OK':'PENDING'} →</span></button>`).join('')||'<div class="empty">Belum ada child region.</div>'}</div>`;d.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{const level=b.dataset.level;const next2=level==='city'?'district':level==='district'?'village':null;if(next2)drill(b.dataset.id,b.querySelector('b').textContent,next2);else showRegionProfile(b.dataset.id,b.querySelector('b').textContent,level)});}catch(e){d.innerHTML=`<div class="empty"><b>Drill-down gagal.</b><small>${esc(e.message)}</small></div>`}}
function showRegionProfile(id,name,level){const d=$('region-detail');d.innerHTML=`<div class="subcrumb"><b>${esc(name)}</b><span>${esc(level)}</span></div><div class="kpirow"><div class="kpi"><small>WILAYAH</small><b>${esc(name)}</b><span>BIG registry</span></div><div class="kpi"><small>BOUNDARY</small><b>READY</b><span>status dari registry</span></div><div class="kpi"><small>MASALAH</small><b>—</b><span>menunggu evidence</span></div></div><div class="notice">Wilayah ini menjadi pintu masuk ke data, masalah, laporan warga, analisis dan solusi.</div><button class="btn-primary" data-view="report">Laporkan masalah di wilayah ini</button>`;bindViews();}

async function renderProblems(){pageInto('problems',shell('problems',`<div class="tabs"><button class="tab active" data-problem-tab="latest">Terkini</button><button class="tab" data-problem-tab="impact">Dampak tinggi</button><button class="tab" data-problem-tab="unresolved">Belum terselesaikan</button></div><div id="problem-content"><div class="loading">Memuat daftar masalah…</div></div>`));const tabs=document.querySelectorAll('[data-problem-tab]');tabs.forEach(t=>t.onclick=()=>{tabs.forEach(x=>x.classList.remove('active'));t.classList.add('active');loadProblems(t.dataset.problemTab)});await loadProblems('latest');}
async function loadProblems(mode){const box=$('problem-content');box.innerHTML='<div class="loading">Mencari masalah…</div>';try{let path='/rest/v1/problems?select=id,title,category,status,confidence,impact_score,first_detected_at,last_observed_at&order=updated_at.desc&limit=30';if(mode==='impact')path+='&impact_score=gte.70';if(mode==='unresolved')path+='&status=not.eq.resolved';const rows=await supabase(path);box.innerHTML=rows.length?`<div class="list">${rows.map(r=>`<button class="issue-card" data-problem-id="${esc(r.id)}"><div><span class="tag blue">${esc(r.category||'Masalah')}</span><h3>${esc(r.title)}</h3><small>${esc(r.status||'detected')} • confidence ${esc(r.confidence??'—')} • impact ${esc(r.impact_score??'—')}</small></div><span>→</span></button>`).join('')}</div>`:'<div class="empty"><b>Belum ada masalah produksi yang bisa ditampilkan.</b><small>Masalah muncul setelah evidence tervalidasi.</small></div>';box.querySelectorAll('[data-problem-id]').forEach(b=>b.onclick=()=>problemDetail(b.dataset.problemId));}catch(e){box.innerHTML=`<div class="empty"><b>Belum bisa membaca Problem Engine.</b><small>${esc(e.message)}</small></div>`}}
async function problemDetail(id){const box=$('problem-content');box.innerHTML='<div class="loading">Membuka detail masalah…</div>';try{const rows=await supabase(`/rest/v1/problems?select=*&id=eq.${encodeURIComponent(id)}&limit=1`);const p=rows[0];if(!p)throw Error('Masalah tidak ditemukan');box.innerHTML=`<div class="card detail-card"><div class="cardhead"><span class="tag red">${esc(p.status||'detected')}</span><span>${esc(p.category||'—')}</span></div><h3>${esc(p.title)}</h3><div class="kpirow"><div class="kpi"><small>CONFIDENCE</small><b>${esc(p.confidence??'—')}</b></div><div class="kpi"><small>IMPACT</small><b>${esc(p.impact_score??'—')}</b></div><div class="kpi"><small>LAST OBSERVED</small><b>${p.last_observed_at?new Date(p.last_observed_at).toLocaleString('id-ID'):'—'}</b></div></div></div>`}catch(e){box.innerHTML=`<div class="empty"><b>Detail gagal dibuka.</b><small>${esc(e.message)}</small></div>`}}

async function renderData(){pageInto('data',shell('data',`<div class="stats"><div><small>PROVINSI</small><b>38</b><span>registry BIG</span></div><div><small>KAB / KOTA</small><b>514</b><span>registry BIG</span></div><div><small>KECAMATAN</small><b>7.282</b><span>registry BIG</span></div><div><small>DESA / KEL</small><b>83.529</b><span>registry BIG</span></div></div><div class="grid2"><div class="card"><div class="cardhead"><b>DATA TRUST</b><b id="trust-score">100%</b></div><div class="meter"><i style="width:100%"></i></div><div class="notice success">Registry wilayah dan parent-child linkage tersedia. Boundary terus diproses bertahap.</div></div><div class="card"><div class="cardhead"><b>SOURCES</b><span>traceable</span></div><div class="notice">Sumber wilayah utama: BIG. Metadata, status sinkronisasi, waktu observasi, dan geometry hash tersimpan pada registry.</div></div></div>`));}

function renderReport(prefill=''){pageInto('report',shell('report',`<div class="card report-form"><h3>Laporkan Masalah di Sekitar Anda</h3><p class="muted">Laporan warga adalah sinyal awal. Sistem akan memisahkan cerita, bukti, verifikasi, dan fakta produksi.</p><label>Judul masalah<input id="report-title" value="${esc(prefill)}" placeholder="Contoh: Jalan rusak di dusun…"></label><label>Deskripsi<textarea id="report-body" rows="6" placeholder="Ceritakan apa yang terjadi, sejak kapan, dan dampaknya…"></textarea></label><div class="grid2"><label>Wilayah<input id="report-region" placeholder="Desa / Kecamatan / Kabupaten"></label><label>Kategori<select id="report-cat"><option>Infrastruktur</option><option>Ekonomi</option><option>Pendidikan</option><option>Kesehatan</option><option>Lingkungan</option><option>Sosial</option></select></label></div><button id="report-submit" class="btn-primary">Kirim Laporan</button><div id="report-status" class="notice" style="display:none"></div></div>`));$('report-submit').onclick=submitReport;}
function submitReport(){const title=$('report-title').value.trim(),body=$('report-body').value.trim(),region=$('report-region').value.trim(),category=$('report-cat').value;if(!title||!body){$('report-status').style.display='block';$('report-status').textContent='Judul dan deskripsi wajib diisi.';return}const item={id:crypto.randomUUID(),title,body,region,category,created_at:new Date().toISOString(),status:'submitted'};const rows=JSON.parse(localStorage.getItem('ipm_reports')||'[]');rows.unshift(item);localStorage.setItem('ipm_reports',JSON.stringify(rows.slice(0,100)));$('report-status').style.display='block';$('report-status').className='notice success';$('report-status').innerHTML='<b>Laporan tersimpan di perangkat ini.</b> Pada tahap berikutnya laporan dapat dikirim ke backend/ingestion resmi.';}

function simplePage(id,k){pageInto(id,shell(k,`<div class="grid2"><div class="card"><h3>Terhubung dengan sistem inti</h3><p class="muted">Modul ini menjadi antarmuka untuk data, evidence, pola, forecast, dan rekomendasi. Konten produksi akan muncul ketika pipeline menyediakan evidence tervalidasi.</p></div><div class="card"><h3>Status</h3><div class="notice success">Antarmuka aktif dan siap terhubung.</div></div></div>`));}

function renderSearch(text){pageInto('result',`<div class="page"><span class="eyebrow">PENCARIAN</span><h2>Hasil untuk “${esc(text)}”</h2><p class="muted">Pencarian mengirim pertanyaan ke API/orchestrator.</p><div id="search-result" class="card"><div class="loading">Mengumpulkan evidence…</div></div></div>`);fetch('/api/ask?q='+encodeURIComponent(text)).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d?.detail||'API error');$('search-result').innerHTML=`<div class="tag">HASIL ANALISIS</div><h3>${esc(d.summary||'Analisis selesai')}</h3><p><b>Confidence:</b> ${esc(d.confidence??'—')}% · <b>Evidence:</b> ${esc(d.evidence_strength??'—')}</p>${Array.isArray(d.sources)?`<div class="list">${d.sources.map(s=>`<div class="issue-row"><div><b>${esc(s.source)}</b><small>${esc(s.metric)}: ${esc(s.value)} ${esc(s.unit)}</small></div></div>`).join('')}</div>`:''}<p><b>Ketidakpastian:</b> ${Array.isArray(d.uncertainty)?d.uncertainty.map(esc).join(' · '):'—'}</p>`}).catch(e=>{$('search-result').innerHTML=`<div class="empty"><b>API belum mengembalikan hasil.</b><small>${esc(e.message)}</small></div>`});}

async function renderMap(){pageInto('map',shell('regions',`<div class="card"><div class="cardhead"><div><b>PETA INDONESIA</b><p class="muted">Peta interaktif untuk menjelajahi Indonesia.</p></div><button class="btn-primary" data-view="regions">Jelajahi Wilayah</button></div><div class="map big" id="full-map"></div><div class="notice success">Peta dapat dizoom, digeser, dan dipilih marker/lokasi.</div></div>`));if(window.L){const m=L.map('full-map',{zoomControl:true,scrollWheelZoom:true,minZoom:4,maxZoom:12}).setView([-2.5,118],4.8);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(m);L.marker([-6.1754,106.8272]).addTo(m).bindPopup('<b>Jakarta</b><br>Contoh titik interaktif').openPopup();L.marker([-7.7972,110.3688]).addTo(m).bindPopup('<b>Yogyakarta</b><br>Contoh titik interaktif');}}

async function render(view,extra=''){switch(view){case'home':setActive('home');break;case'regions':await renderRegions();break;case'problems':await renderProblems();break;case'data':await renderData();break;case'report':renderReport(extra);break;case'map':await renderMap();break;case'monitoring':simplePage('monitoring','monitoring');break;case'intelligence':simplePage('intelligence','intelligence');break;case'solutions':simplePage('solutions','solutions');break;case'account':simplePage('account','account');break;case'more':simplePage('more','more');break;default:setActive('home')}}

function ask(){const q=$('question');const text=q?.value.trim();if(text)renderSearch(text)}
function bindHome(){const q=$('question'),btn=$('ask');document.querySelectorAll('[data-q]').forEach(x=>x.onclick=()=>{q.value=x.dataset.q;ask()});if(btn)btn.onclick=ask;if(q)q.addEventListener('keydown',e=>{if(e.key==='Enter')ask()});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>render(b.dataset.view));const mobile=$('mobileMenu');if(mobile)mobile.onclick=()=>{const n=$('mainNav');if(n)n.classList.toggle('open')};const hs=$('headerSearch');if(hs)hs.onclick=()=>{q?.focus();window.scrollTo({top:0,behavior:'smooth'})};}

if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{bindHome();if(window.lucide)window.lucide.createIcons()});else{bindHome();if(window.lucide)window.lucide.createIcons()}
