(()=>{
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const SUPABASE_URL='https://gfggmkeucgqkkyvummpu.supabase.co';
const SUPABASE_KEY='sb_publishable_ptCVbq9h15prKhT0OO5Zmg_LkE3cb0';
async function q(path){const r=await fetch(SUPABASE_URL+path,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,Accept:'application/json'}});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
const MENUS=[
 {view:'home',label:'Beranda'},
 {label:'Jelajahi Indonesia',children:[{view:'map',label:'Peta Indonesia'},{view:'regions',label:'Wilayah',children:[{view:'regions',label:'Provinsi'},{view:'regions',label:'Kabupaten / Kota'},{view:'regions',label:'Kecamatan'},{view:'regions',label:'Desa / Kelurahan'},{view:'regions',label:'Dusun'}]}]},
 {label:'Masalah',children:[{view:'problems',label:'Terkini'},{view:'problems',label:'Berdasarkan Wilayah',children:[{view:'regions',label:'Provinsi'},{view:'regions',label:'Kabupaten / Kota'},{view:'regions',label:'Kecamatan'},{view:'regions',label:'Desa / Kelurahan'}]},{view:'problems',label:'Berdasarkan Kategori',children:[{view:'problems',label:'Ekonomi'},{view:'problems',label:'Sosial'},{view:'problems',label:'Kesehatan'},{view:'problems',label:'Infrastruktur'},{view:'problems',label:'Pendidikan'},{view:'problems',label:'Lingkungan'}]},{view:'problems',label:'Mendesak'},{view:'problems',label:'Belum Terselesaikan'}]},
 {label:'Data & Statistik',children:[{view:'data',label:'Nasional'},{view:'data',label:'Provinsi'},{view:'data',label:'Kabupaten / Kota'},{view:'data',label:'Kecamatan'},{view:'data',label:'Desa / Kelurahan'},{view:'data',label:'Indikator'},{view:'data',label:'Perbandingan'}]},
 {label:'Suara Warga',children:[{view:'report',label:'Laporkan Masalah'},{view:'report',label:'Cerita Warga'},{view:'report',label:'Keluhan'},{view:'report',label:'Usulan'},{view:'report',label:'Polling'},{view:'report',label:'Diskusi'}]},
 {label:'Pantau Perubahan',children:[{view:'monitoring',label:'Masalah Baru'},{view:'monitoring',label:'Meningkat'},{view:'monitoring',label:'Menurun'},{view:'monitoring',label:'Ramai Dibicarakan'},{view:'monitoring',label:'Peringatan'}]},
 {label:'Wawasan',children:[{view:'intelligence',label:'Pola'},{view:'intelligence',label:'Penyebab'},{view:'intelligence',label:'Tren'},{view:'intelligence',label:'Hubungan'},{view:'intelligence',label:'Ringkasan Wilayah'}]},
 {label:'Kemungkinan',children:[{view:'future',label:'Perkiraan'},{view:'future',label:'Perbandingan'},{view:'future',label:'Skenario'}]},
 {label:'Solusi',children:[{view:'solutions',label:'Solusi Warga'},{view:'solutions',label:'Solusi Pemerintah'},{view:'solutions',label:'Praktik Baik'},{view:'solutions',label:'Evaluasi Hasil'}]},
 {label:'Lainnya',children:[{view:'more',label:'Tentang'},{view:'more',label:'Cara Kerja'},{view:'more',label:'Kebijakan'},{view:'account',label:'Akun'}]}
];
function css(){if($('ipm-premium-public'))return;const s=document.createElement('style');s.id='ipm-premium-public';s.textContent=`
:root{--ipm-navy:#0d2038;--ipm-red:#c9273d;--ipm-blue:#2563a6;--ipm-ink:#26364b;--ipm-muted:#738196;--ipm-line:#e4e9ef;--ipm-soft:#f5f7fa}
body{background:#f6f8fb}.header{position:sticky;top:0;z-index:10000;background:rgba(255,255,255,.97);backdrop-filter:blur(18px);border-bottom:1px solid rgba(13,32,56,.08);box-shadow:0 6px 24px rgba(13,32,56,.05)}.header .brand{flex:0 0 auto}.main-nav.ipm-nav{display:flex;align-items:center;justify-content:flex-start;gap:3px;flex:1;min-width:0;margin-left:28px;overflow:visible}.ipm-menu{position:relative}.ipm-menu>button{border:0;background:transparent;color:#314159;padding:11px 9px;border-radius:10px;font:650 12.5px/1 Inter,system-ui,sans-serif;white-space:nowrap;cursor:pointer}.ipm-menu>button:hover,.ipm-menu.open>button{background:#f1f4f7;color:var(--ipm-navy)}.ipm-menu.home>button{font-weight:800;color:var(--ipm-navy)}.ipm-sub{position:absolute;top:calc(100% + 8px);left:0;min-width:235px;background:#fff;border:1px solid var(--ipm-line);border-radius:15px;padding:7px;box-shadow:0 24px 60px rgba(13,32,56,.15);display:none;z-index:11000}.ipm-menu.open>.ipm-sub,.ipm-subitem:hover>.ipm-sub{display:block}.ipm-subitem{position:relative}.ipm-subitem>button{width:100%;border:0;background:transparent;color:#334359;padding:10px 12px;border-radius:9px;text-align:left;display:flex;align-items:center;justify-content:space-between;gap:18px;font:550 13px/1.25 Inter,system-ui,sans-serif;cursor:pointer}.ipm-subitem>button:hover{background:#f4f7f9}.ipm-sub .ipm-sub{top:-7px;left:calc(100% + 7px)}.ipm-arrow{opacity:.48}.header-actions{flex:0 0 auto;display:flex;gap:8px;align-items:center}.header-actions .btn-outline,.header-actions .btn-primary{white-space:nowrap}
#home{background:#f6f8fb}.ipm-home{max-width:1280px;margin:0 auto;padding:0 28px 84px}.ipm-hero{margin-top:18px;background:linear-gradient(135deg,#0e223b 0%,#183d63 68%,#234e77 100%);border-radius:24px;overflow:hidden;min-height:285px;position:relative;box-shadow:0 18px 48px rgba(13,32,56,.14)}.ipm-hero:before{content:'';position:absolute;inset:auto -5% 0 38%;height:72%;background:radial-gradient(circle at 50% 60%,rgba(255,255,255,.14),transparent 60%)}.ipm-hero-copy{position:relative;z-index:2;max-width:730px;padding:38px 44px}.ipm-kicker{font-size:10px;font-weight:850;letter-spacing:.16em;text-transform:uppercase;color:#bfcfdf}.ipm-hero h1{margin:9px 0 8px;color:#fff;font-size:clamp(39px,4.8vw,64px);line-height:1.02;letter-spacing:-.05em}.ipm-hero p{margin:0;color:#dce6ef;font-size:16px;line-height:1.6}.ipm-search{margin-top:20px;display:flex;align-items:center;gap:10px;background:#fff;border-radius:13px;padding:5px 6px 5px 15px;box-shadow:0 12px 35px rgba(0,0,0,.14)}.ipm-search input{flex:1;border:0;outline:0;font:500 14px Inter;color:#26364b}.ipm-search button{border:0;background:var(--ipm-red);color:#fff;border-radius:10px;padding:11px 17px;font-weight:750}.ipm-chips{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.ipm-chip{border:1px solid rgba(255,255,255,.2);background:rgba(255,255,255,.08);color:#eef4fa;padding:6px 10px;border-radius:999px;font-size:10px}
.ipm-section{margin-top:28px}.ipm-head{display:flex;align-items:flex-end;justify-content:space-between;gap:22px;margin-bottom:14px}.ipm-head h2{margin:5px 0 0;color:var(--ipm-navy);font-size:clamp(25px,2.6vw,34px);line-height:1.1;letter-spacing:-.04em}.ipm-head p{max-width:650px;margin:7px 0 0;color:var(--ipm-muted);line-height:1.55}.ipm-link{border:0;background:none;color:var(--ipm-blue);font-weight:750;cursor:pointer;white-space:nowrap}
.ipm-problems{display:grid;grid-template-columns:1.2fr .9fr .9fr;gap:14px}.ipm-lead,.ipm-problem{background:#fff;border:1px solid var(--ipm-line);border-radius:18px;box-shadow:0 10px 28px rgba(13,32,56,.05)}.ipm-lead{padding:22px}.ipm-alert{display:inline-flex;padding:7px 10px;border-radius:999px;background:#fff0f2;color:#b42332;font-size:10px;font-weight:850}.ipm-lead h3{margin:12px 0 7px;color:var(--ipm-navy);font-size:24px;letter-spacing:-.03em}.ipm-lead p{margin:0;color:var(--ipm-muted);line-height:1.6}.ipm-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:18px}.ipm-metric{background:var(--ipm-soft);border-radius:11px;padding:10px}.ipm-metric b{display:block;color:var(--ipm-navy);font-size:19px}.ipm-metric span{font-size:10px;color:#78879a}.ipm-problem{padding:16px}.ipm-problem .thumb{height:100px;border-radius:13px;background:linear-gradient(135deg,#eef2f6,#e5ecf4);display:grid;place-items:center;font-size:32px}.ipm-problem .tag{display:inline-flex;margin-top:11px;padding:5px 8px;border-radius:999px;background:#eef5ff;color:var(--ipm-blue);font-size:9px;font-weight:850}.ipm-problem h4{margin:8px 0 6px;color:var(--ipm-navy);font-size:16px}.ipm-problem p{margin:0;color:#77869a;font-size:12px;line-height:1.5}
.ipm-voice{display:grid;grid-template-columns:1.2fr .85fr .8fr;gap:18px;align-items:center;background:linear-gradient(135deg,#0d2038,#1d4b78);border-radius:20px;padding:24px;color:#fff;box-shadow:0 17px 42px rgba(13,32,56,.14)}.ipm-voice h3{margin:0;font-size:26px;letter-spacing:-.035em}.ipm-voice p{margin:7px 0 0;color:#d6e1ec;line-height:1.55}.ipm-voice-actions{display:flex;gap:8px;flex-wrap:wrap}.ipm-voice .btn-primary{background:#fff;color:var(--ipm-navy)}.ipm-voice .btn-outline{color:#fff;border-color:rgba(255,255,255,.3)}.ipm-comment{padding:14px 15px;border:1px solid rgba(255,255,255,.13);background:rgba(255,255,255,.08);border-radius:14px}.ipm-comment b{display:block;font-size:14px}.ipm-comment span{display:block;margin-top:5px;font-size:11px;color:#c9d6e3;line-height:1.5}
.ipm-3{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.ipm-card{background:#fff;border:1px solid var(--ipm-line);border-radius:18px;padding:20px;box-shadow:0 10px 28px rgba(13,32,56,.045)}.ipm-card .ico{width:40px;height:40px;border-radius:11px;background:#eef4fa;display:grid;place-items:center;color:var(--ipm-navy);font-size:18px}.ipm-card h3{margin:12px 0 7px;color:var(--ipm-navy);font-size:18px}.ipm-card p{margin:0;color:#6f7f94;font-size:12.5px;line-height:1.6}.ipm-card button{margin-top:13px}.ipm-two{display:grid;grid-template-columns:1fr 1fr;gap:14px}.ipm-panel{background:#fff;border:1px solid var(--ipm-line);border-radius:18px;padding:22px;box-shadow:0 10px 28px rgba(13,32,56,.045)}.ipm-panel h3{margin:0 0 8px;color:var(--ipm-navy);font-size:22px}.ipm-panel p{margin:0;color:#6e7e93;line-height:1.6}.ipm-map-mini{min-height:250px;background:linear-gradient(145deg,#e6eef6,#f8fafc);border-radius:15px;position:relative;overflow:hidden}.ipm-map-mini:before{content:'';position:absolute;inset:25px 35px;background:linear-gradient(35deg,transparent 25%,rgba(37,99,166,.12) 26%,rgba(37,99,166,.12) 27%,transparent 28%),linear-gradient(145deg,transparent 31%,rgba(37,99,166,.1) 32%,rgba(37,99,166,.1) 33%,transparent 34%);border-radius:40% 55% 45% 50%}.ipm-map-mini:after{content:'INDONESIA';position:absolute;right:16px;bottom:13px;color:#7a889a;font-size:10px;font-weight:850;letter-spacing:.14em}.ipm-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:16px}.ipm-stats div{background:var(--ipm-soft);border-radius:10px;padding:10px}.ipm-stats b{display:block;font-size:19px;color:var(--ipm-navy)}.ipm-stats span{font-size:10px;color:#78879a}.ipm-cta{margin-top:28px;background:#fff;border:1px solid var(--ipm-line);border-radius:20px;padding:30px;text-align:center;box-shadow:0 10px 30px rgba(13,32,56,.045)}.ipm-cta h2{margin:0;color:var(--ipm-navy);font-size:31px;letter-spacing:-.04em}.ipm-cta p{max-width:650px;margin:9px auto 16px;color:#6f7f93;line-height:1.6}.ipm-cta-actions{display:flex;justify-content:center;gap:9px;flex-wrap:wrap}
@media(max-width:980px){.ipm-problems,.ipm-voice,.ipm-two{grid-template-columns:1fr}.ipm-3{grid-template-columns:1fr}.ipm-head{display:block}.ipm-metrics,.ipm-stats{grid-template-columns:repeat(2,1fr)}}
@media(max-width:820px){.main-nav.ipm-nav{display:none;position:absolute;top:calc(100% + 8px);left:12px;right:12px;margin:0;flex-direction:column;align-items:stretch;background:#fff;border:1px solid var(--ipm-line);border-radius:16px;padding:8px;box-shadow:0 22px 55px rgba(13,32,56,.18);max-height:78vh;overflow:auto}.main-nav.ipm-nav.mobile-open{display:flex}.ipm-menu{display:block}.ipm-menu>button{width:100%;display:flex;justify-content:space-between;padding:11px 12px;font-size:13px}.ipm-menu>.ipm-sub,.ipm-subitem>.ipm-sub{position:static;display:none;box-shadow:none;border:0;border-top:1px solid #edf1f5;border-radius:0;min-width:0;padding:4px 0 4px 10px}.ipm-menu.open>.ipm-sub,.ipm-subitem.mobile-open>.ipm-sub{display:block}.ipm-subitem:hover>.ipm-sub{display:none}.header-actions .icon-btn{display:none}}
`;
document.head.appendChild(s)}
function closeNav(){document.querySelectorAll('.ipm-menu.open').forEach(x=>x.classList.remove('open'));document.querySelectorAll('.ipm-subitem.mobile-open').forEach(x=>x.classList.remove('mobile-open'))}
function buildNav(){const nav=$('mainNav');if(!nav)return;nav.className='main-nav ipm-nav';nav.innerHTML='';const build=items=>{const s=document.createElement('div');s.className='ipm-sub';items.forEach(item=>{const row=document.createElement('div');row.className='ipm-subitem';const b=document.createElement('button');b.type='button';b.textContent=item.label;if(item.children){const a=document.createElement('span');a.className='ipm-arrow';a.textContent='›';b.appendChild(a);b.onclick=e=>{e.stopPropagation();row.classList.toggle('mobile-open')};row.appendChild(b);row.appendChild(build(item.children))}else{b.onclick=e=>{e.stopPropagation();closeNav();window.render?.(item.view)};row.appendChild(b)}s.appendChild(row)});return s};MENUS.forEach(item=>{const m=document.createElement('div');m.className='ipm-menu'+(!item.children?' home':'');const b=document.createElement('button');b.type='button';b.textContent=item.label;if(item.children){const a=document.createElement('span');a.className='ipm-arrow';a.textContent='⌄';b.appendChild(a);b.onclick=e=>{e.stopPropagation();const was=m.classList.contains('open');document.querySelectorAll('.ipm-menu.open').forEach(x=>x.classList.remove('open'));m.classList.toggle('open',!was)};m.appendChild(b);m.appendChild(build(item.children))}else{b.onclick=()=>window.render?.('home');m.appendChild(b)}nav.appendChild(m)});document.addEventListener('click',closeNav,{passive:true})}
function renderHome(){const h=$('home');if(!h)return;h.innerHTML=`<div class="ipm-home"><section class="ipm-hero"><div class="ipm-hero-copy"><span class="ipm-kicker">Portal Data & Aspirasi Publik</span><h1>Indonesia Punya Masalah</h1><p>Lihat pokok masalah Indonesia terlebih dahulu. Setelah itu dengarkan suara warga, ikuti perubahan, dan bersama-sama mencari solusi.</p><div class="ipm-search"><span>⌕</span><input id="ipm-q" placeholder="Cari masalah, daerah, desa, kecamatan, atau topik…"><button id="ipm-search-btn">Cari</button></div><div class="ipm-chips"><button class="ipm-chip" data-q="Kemiskinan">Kemiskinan</button><button class="ipm-chip" data-q="Pendidikan">Pendidikan</button><button class="ipm-chip" data-q="Kesehatan">Kesehatan</button><button class="ipm-chip" data-q="Infrastruktur">Infrastruktur</button><button class="ipm-chip" data-q="Lingkungan">Lingkungan</button><button class="ipm-chip" data-q="Ekonomi">Ekonomi</button></div></div></section>
<section class="ipm-section"><div class="ipm-head"><div><span class="ipm-kicker">POKOK MASALAH INDONESIA</span><h2>Apa yang sedang dihadapi masyarakat?</h2><p>Mulai dari isu yang paling dekat dengan warga. Lihat apa yang terjadi dan masalah mana yang membutuhkan perhatian.</p></div><button class="ipm-link" data-view="problems">Lihat Semua Masalah →</button></div><div class="ipm-problems"><article class="ipm-lead"><span class="ipm-alert">● PERHATIAN PUBLIK</span><h3>Masalah nyata harus terlihat sebelum dicari solusinya.</h3><p>Ruang utama portal menempatkan pokok masalah di depan. Data dan analisis kemudian membantu memberi konteks yang lebih lengkap.</p><div class="ipm-metrics"><div class="ipm-metric"><b>38</b><span>Provinsi</span></div><div class="ipm-metric"><b>514</b><span>Kabupaten/Kota</span></div><div class="ipm-metric"><b>7.282</b><span>Kecamatan</span></div><div class="ipm-metric"><b>83.529</b><span>Desa/Kelurahan</span></div></div></article><article class="ipm-problem"><div class="thumb">🛣️</div><span class="tag">Infrastruktur</span><h4>Masalah infrastruktur di wilayah warga</h4><p>Indonesia</p></article><article class="ipm-problem"><div class="thumb">🛒</div><span class="tag">Ekonomi</span><h4>Tekanan ekonomi rumah tangga</h4><p>Indonesia</p></article></div><div class="ipm-problems ipm-problems-2" style="margin-top:14px"><article class="ipm-problem"><div class="thumb">🏫</div><span class="tag">Pendidikan</span><h4>Akses pendidikan belum merata</h4><p>Indonesia</p></article><article class="ipm-problem"><div class="thumb">🌧️</div><span class="tag">Lingkungan</span><h4>Risiko banjir dan lingkungan</h4><p>Indonesia</p></article><article class="ipm-problem"><div class="thumb">🏥</div><span class="tag">Kesehatan</span><h4>Akses layanan kesehatan</h4><p>Indonesia</p></article></div></section>
<section class="ipm-section"><div class="ipm-voice"><div><span class="ipm-kicker">SUARA WARGA</span><h3>Setelah melihat masalah, mari dengarkan manusianya.</h3><p>Ceritakan pengalaman, beri konteks, sampaikan keluhan, usulan, atau tanggapan terhadap masalah yang sedang dibahas.</p></div><div class="ipm-voice-actions"><button class="btn-primary" data-view="report">＋ Sampaikan Suara</button><button class="btn-outline" data-view="report">Lihat Percakapan →</button></div><div class="ipm-comment"><b>💬 Ayo ikut berkomentar</b><span>Tambahkan pendapat, pengalaman, atau informasi yang membantu masalah dibaca lebih lengkap.</span></div></div></section>
<section class="ipm-section"><div class="ipm-head"><div><span class="ipm-kicker">PANTAU PERUBAHAN</span><h2>Apa yang berubah setelah dibicarakan?</h2><p>Ikuti masalah baru, masalah yang meningkat atau menurun, isu yang ramai dibicarakan, dan hal yang membutuhkan perhatian.</p></div><button class="ipm-link" data-view="monitoring">Pantau Semua →</button></div><div class="ipm-3"><article class="ipm-card"><div class="ico">↗</div><h3>Masalah yang ikut bergerak</h3><p>Perubahan ditampilkan berdasarkan waktu dan wilayah agar perkembangan tidak berhenti sebagai satu laporan.</p><button class="ipm-link" data-view="monitoring">Buka Pantauan →</button></article><article class="ipm-card"><div class="ico">⚠</div><h3>Tren & perhatian</h3><p>Lihat isu yang sedang naik, menurun, atau perlu diperhatikan lebih dekat.</p><button class="ipm-link" data-view="monitoring">Lihat Tren →</button></article><article class="ipm-card"><div class="ico">◌</div><h3>Ringkasan wilayah</h3><p>Bandingkan kondisi antarwilayah dengan bahasa yang mudah dipahami.</p><button class="ipm-link" data-view="regions">Jelajahi Wilayah →</button></article></div></section>
<section class="ipm-section"><div class="ipm-two"><div class="ipm-panel"><div class="ipm-map-mini"></div><div style="margin-top:16px"><span class="ipm-kicker">INDONESIA DALAM SATU PANDANGAN</span><h3>Semakin dekat ke wilayah, semakin jelas masalahnya.</h3><p>Gunakan peta dan hierarki wilayah untuk berpindah dari Indonesia ke provinsi, kabupaten/kota, kecamatan, desa/kelurahan hingga dusun.</p><div style="margin-top:13px"><button class="btn-primary" data-view="map">Peta Indonesia</button> <button class="btn-outline" data-view="regions">Jelajahi wilayah →</button></div></div><div class="ipm-stats"><div><b>38</b><span>Provinsi</span></div><div><b>514</b><span>Kab/Kota</span></div><div><b>7.282</b><span>Kecamatan</span></div><div><b>83.529</b><span>Desa/Kel</span></div></div></div><div class="ipm-panel"><span class="ipm-kicker">DARI MASALAH KE PEMAHAMAN</span><h3>Data, Wawasan, Kemungkinan, dan Solusi.</h3><p>Semua fitur tetap tersedia, tetapi disajikan mengikuti kebutuhan pembaca: memahami masalah, mendengar warga, melihat perubahan, memahami pola, melihat kemungkinan, lalu mencari solusi.</p><div class="ipm-list" style="display:grid;gap:8px;margin-top:15px"><button class="ipm-link" data-view="data" style="text-align:left;background:var(--ipm-soft);padding:12px;border-radius:10px">Data & Statistik →</button><button class="ipm-link" data-view="intelligence" style="text-align:left;background:var(--ipm-soft);padding:12px;border-radius:10px">Wawasan →</button><button class="ipm-link" data-view="future" style="text-align:left;background:var(--ipm-soft);padding:12px;border-radius:10px">Kemungkinan →</button><button class="ipm-link" data-view="solutions" style="text-align:left;background:var(--ipm-soft);padding:12px;border-radius:10px">Solusi & Aksi →</button></div></div></div></section>
<section class="ipm-section"><div class="ipm-cta"><span class="ipm-kicker">INDONESIA PUNYA MASALAH</span><h2>Lihat. Dengarkan. Pahami. Cari solusi.</h2><p>Satu ruang publik untuk memahami masalah Indonesia berdasarkan wilayah, data, suara masyarakat, perubahan, dan tindakan.</p><div class="ipm-cta-actions"><button class="btn-primary" data-view="report">Sampaikan Masalah</button><button class="btn-outline" data-view="map">Jelajahi Indonesia →</button></div></div></section></div>`;
 bindHome();loadProblemHighlights()}
function bindHome(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>window.render?.(b.dataset.view));document.querySelectorAll('.ipm-chip').forEach(b=>b.onclick=()=>{$('ipm-q').value=b.dataset.q;$('ipm-search-btn').click()});const run=()=>{const t=$('ipm-q').value.trim();if(t&&window.render)window.render('result',t)};$('ipm-search-btn')?.addEventListener('click',run);$('ipm-q')?.addEventListener('keydown',e=>{if(e.key==='Enter')run()})}
async function loadProblemHighlights(){try{const rows=await q('/rest/v1/problems?select=id,title,category,status,impact_score&order=updated_at.desc&limit=5');const cards=document.querySelectorAll('.ipm-problem');rows.slice(0,5).forEach((r,i)=>{const c=cards[i]||cards[i%cards.length];if(!c)return;c.dataset.problemId=r.id;const tag=c.querySelector('.tag');const h=c.querySelector('h4');const p=c.querySelector('p');if(tag)tag.textContent=r.category||'Masalah';if(h)h.textContent=r.title;if(p)p.textContent=(r.status||'Terkini')+(r.impact_score!=null?` · dampak ${r.impact_score}`:'');c.style.cursor='pointer';c.onclick=()=>window.render?.('problems')})}catch{}}
function cleanFooter(){const f=document.querySelector('.footer');if(!f)return;f.innerHTML=`<div class="footer-brand"><span class="brand-mark"><i></i><b></b></span><strong>INDONESIA<br>PUNYA MASALAH</strong><span>Dari Rakyat, Untuk Indonesia</span></div><div class="footer-links"><button data-view="home">Beranda</button><button data-view="map">Peta Indonesia</button><button data-view="problems">Masalah</button><button data-view="report">Suara Warga</button><button data-view="data">Data & Statistik</button><button data-view="monitoring">Pantau Perubahan</button><button data-view="solutions">Solusi</button><button data-view="more">Tentang Kami</button></div><small>© 2026 Indonesia Punya Masalah • Data dan sumber harus dapat ditelusuri.</small>`;document.querySelectorAll('.footer [data-view]').forEach(b=>b.onclick=()=>window.render?.(b.dataset.view))}
function activate(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(v)?.classList.add('active');document.querySelectorAll('.ipm-menu').forEach(x=>x.classList.remove('active'));window.scrollTo({top:0,behavior:'smooth'});try{window.lucide?.createIcons()}catch{}}
function install(){css();buildNav();cleanFooter();renderHome();const base=window.render;if(typeof base==='function'&&!base.__ipmPublic){const wrapped=async(v,x='')=>{if(v==='control')v='home';if(v==='home'){renderHome();activate('home');return}const r=base(v,x);try{await r}finally{setTimeout(()=>{document.querySelectorAll('[data-view="control"]').forEach(e=>e.remove());},0)}return r};wrapped.__ipmPublic=true;window.render=wrapped}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
