(()=>{
'use strict';
const U='https://gfggmkeucgqkkyvummpu.supabase.co',K='sb_publishable_ptCVbq9h15prKhT0OO5Zmg_LkE3cbK0';
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
async function q(path){const r=await fetch(U+path,{headers:{apikey:K,Authorization:`Bearer ${K}`,Accept:'application/json'}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(typeof d==='string'?d:(d?.message||`HTTP ${r.status}`));return d}
function activate(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id)?.classList.add('active');document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
function wire(){document.querySelectorAll('[data-public-flow]').forEach(b=>b.onclick=()=>window.render?.(b.dataset.publicFlow,b.dataset.arg||''))}
function shell(title,body){return `<div class="page suite-page public-flow-page"><div class="suite-kicker">PENCARIAN</div><h2>${esc(title)}</h2>${body}</div>`}
async function search(text){const host=document.getElementById('result');if(!host)return;activate('result');host.innerHTML=shell(`Hasil pencarian “${text}”`,`<div class="card suite-panel"><div class="loading">Mencari wilayah dan masalah…</div></div>`);try{const term=encodeURIComponent(text.trim());const [rs,ps]=await Promise.all([q(`/rest/v1/regions?select=id,name,level,admin_code_pum&source_name=eq.BIG&name=ilike.*${term}*&order=level.asc,name.asc&limit=20`),q(`/rest/v1/problems?select=id,title,category,status,confidence,impact_score,updated_at,region_id&title=ilike.*${term}*&order=updated_at.desc&limit=20`)]);const regionHtml=rs?.length?rs.map(x=>`<button class="suite-row suite-button" data-public-flow="region" data-arg="${esc(x.name)}"><div><b>${esc(x.name)}</b><small>${esc(x.level||'Wilayah')} · ${esc(x.admin_code_pum||'')}</small></div><span>→</span></button>`).join(''):'<div class="empty">Tidak ditemukan wilayah.</div>';const problemHtml=ps?.length?ps.map(x=>`<button class="suite-row suite-button" data-public-flow="problem-detail" data-arg="${esc(x.id)}"><div><b>${esc(x.title)}</b><small>${esc(x.category||'Masalah')} · ${esc(x.status||'open')} · diperbarui ${x.updated_at?new Date(x.updated_at).toLocaleDateString('id-ID'):'—'}</small></div><span>→</span></button>`).join(''):'<div class="empty">Tidak ditemukan masalah.</div>';host.innerHTML=shell(`Hasil pencarian “${text}”`,`<div class="search-results"><section class="card suite-panel"><h3>Wilayah</h3>${regionHtml}</section><section class="card suite-panel"><h3>Masalah</h3>${problemHtml}</section></div><div class="detail-actions"><button class="btn-outline" data-public-flow="home">← Kembali</button><button class="btn-primary" data-public-flow="report" data-arg="${esc(text)}">Laporkan informasi terkait</button></div>`);wire()}catch(err){host.innerHTML=shell('Pencarian gagal',`<div class="suite-status warn">${esc(err.message)}</div><button class="btn-outline" data-public-flow="home">Kembali</button>`);wire()}}
const old=window.render;
window.render=async function(v,x=''){if(v==='result'&&String(x).trim())return search(String(x).trim());return typeof old==='function'?old(v,x):undefined};
const css=document.createElement('style');css.textContent=`.public-flow-page{max-width:1180px;margin:0 auto}.public-flow-page .search-results{display:grid;grid-template-columns:1fr 1fr;gap:12px}.public-flow-page .suite-panel h3{margin:0 0 10px;font-size:14px}.public-flow-page .suite-button{width:100%;text-align:left;background:#fff;border:1px solid #e7edf3;cursor:pointer}.public-flow-page .suite-button:hover{background:#f7fbff}.public-flow-page .detail-actions{display:flex;gap:8px;margin-top:12px}@media(max-width:700px){.public-flow-page .search-results{grid-template-columns:1fr}.public-flow-page .detail-actions{flex-wrap:wrap}}`;document.head.appendChild(css);
})();
