(()=>{
'use strict';
const U='https://gfggmkeucgqkkyvummpu.supabase.co',K='sb_publishable_ptCVbq9h15prKhT0OO5Zmg_LkE3cbK0';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
async function q(path,opts={}){const r=await fetch(U+path,{...opts,headers:{apikey:K,Authorization:`Bearer ${K}`,'Content-Type':'application/json',Accept:'application/json',...(opts.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(typeof d==='string'?d:(d?.message||d?.hint||`HTTP ${r.status}`));return d}
function activate(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id)?.classList.add('active');document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
function renderReport(prefill=''){const host=$('report');if(!host)return;host.innerHTML=`<div class="page public-report-page"><span class="eyebrow">SUARA WARGA</span><h2>Ceritakan Masalah di Sekitar Anda</h2><p class="muted">Laporan warga menjadi sinyal awal. Laporan tidak otomatis dianggap sebagai fakta dan tetap melalui proses verifikasi.</p><div class="card report-card"><div class="report-grid"><label>Judul masalah<input id="pr-title" value="${esc(prefill)}" placeholder="Contoh: Jalan rusak di Dusun…"></label><label>Kategori<select id="pr-cat"><option>Infrastruktur</option><option>Ekonomi</option><option>Pendidikan</option><option>Kesehatan</option><option>Lingkungan</option><option>Sosial</option><option>Lainnya</option></select></label><label>Wilayah<input id="pr-region" placeholder="Desa / Kecamatan / Kabupaten / Provinsi"></label><label>Waktu kejadian<input id="pr-time" type="datetime-local"></label><label class="full">Deskripsi / kronologi<textarea id="pr-body" rows="7" placeholder="Apa yang terjadi, sejak kapan, siapa yang terdampak, dan bukti apa yang tersedia?"></textarea></label></div><div class="report-note">✓ Narasi warga dipisahkan dari evidence &nbsp; ✓ Verifikasi diperlukan &nbsp; ✓ Status dapat berubah setelah pemeriksaan</div><button id="pr-submit" class="btn-primary">Kirim Laporan</button><div id="pr-status" class="notice" style="display:none"></div></div></div>`;activate('report');$('pr-submit').onclick=submit;}
async function submit(){const st=$('pr-status'),title=$('pr-title').value.trim(),body=$('pr-body').value.trim(),regionName=$('pr-region').value.trim(),category=$('pr-cat').value;st.style.display='block';if(!title||!body){st.className='notice';st.textContent='Judul dan deskripsi wajib diisi.';return}st.className='notice';st.textContent='Mengirim laporan…';let region_id=null;try{if(regionName){const rows=await q(`/rest/v1/regions?select=id,name&source_name=eq.BIG&name=ilike.*${encodeURIComponent(regionName)}*&limit=1`);region_id=rows?.[0]?.id||null}}catch{}const payload={title,narrative:body,category,region_id,occurred_at:$('pr-time').value?new Date($('pr-time').value).toISOString():new Date().toISOString(),verification_status:'received',classification:'citizen_report'};try{await q('/rest/v1/human_reports',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(payload)});st.className='notice success';st.innerHTML='<b>Laporan diterima.</b> Laporan tersimpan di sistem dan menunggu verifikasi.';localStorage.setItem('ipm_last_report',JSON.stringify({...payload,created_at:new Date().toISOString(),sync:'supabase'}));}catch(err){const rows=JSON.parse(localStorage.getItem('ipm_reports')||'[]');rows.unshift({...payload,id:crypto.randomUUID(),region_name:regionName,created_at:new Date().toISOString(),sync:'local'});localStorage.setItem('ipm_reports',JSON.stringify(rows.slice(0,100)));st.className='notice';st.innerHTML='<b>Tersimpan sementara di perangkat.</b> Server belum menerima penulisan langsung, tetapi laporan tetap tersimpan di perangkat ini.';}}
const old=window.render;window.render=async function(v,x=''){if(v==='report')return renderReport(x);return typeof old==='function'?old(v,x):undefined};window.renderPublicReport=renderReport;
const style=document.createElement('style');style.textContent=`.public-report-page{max-width:900px;margin:0 auto}.report-card{padding:20px}.report-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.report-grid label{font-size:10px;font-weight:800;color:#53677f}.report-grid input,.report-grid select,.report-grid textarea{display:block;width:100%;box-sizing:border-box;margin-top:6px;border:1px solid #dfe7ef;border-radius:10px;padding:11px 12px;background:#fff;font:500 12px Inter;outline:0}.report-grid textarea{resize:vertical}.report-grid .full{grid-column:1/-1}.report-note{margin:14px 0;padding:10px;border-radius:9px;background:#f5f9fd;color:#65778d;font-size:9px}.public-report-page .notice{margin-top:10px}@media(max-width:700px){.report-grid{grid-template-columns:1fr}.report-grid .full{grid-column:auto}}`;document.head.appendChild(style);
})();