(()=>{
'use strict';
const U='https://gfggmkeucgqkkyvummpu.supabase.co',K='sb_publishable_ptCVbq9h15prKhT0OO5Zmg_LkE3cbK0';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
async function q(path){const r=await fetch(U+path,{headers:{apikey:K,Authorization:`Bearer ${K}`,Accept:'application/json'}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(typeof d==='string'?d:(d?.message||`HTTP ${r.status}`));return d}
function shell(k,t,d,b){return `<div class="page suite-page public-region-page"><div class="suite-kicker">${esc(k)}</div><h2>${esc(t)}</h2><p class="muted suite-desc">${esc(d)}</p>${b}</div>`}
function activate(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id)?.classList.add('active');document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
function wire(){document.querySelectorAll('[data-region-action]').forEach(b=>b.onclick=()=>window.render?.(b.dataset.regionAction,b.dataset.arg||''));document.querySelectorAll('[data-problem-id]').forEach(b=>b.onclick=()=>window.render?.('problem-detail',b.dataset.problemId))}
async function renderRegion(name){const host=$('result');if(!host)return;host.innerHTML=shell('WILAYAH',name,'Memuat profil wilayah, masalah publik, dan laporan warga yang tersedia.',`<div class="card suite-panel" id="region-detail"><div class="loading">Memuat wilayah…</div></div>`);activate('result');try{
 const matches=await q(`/rest/v1/regions?select=id,name,level,admin_code_pum,source_name&source_name=eq.BIG&name=ilike.${encodeURIComponent(name)}&limit=8`);const region=matches?.[0];
 if(!region)throw new Error(`Wilayah “${name}” belum ditemukan di registry publik.`);
 let problems=[],reports=[],children=[];
 try{problems=await q(`/rest/v1/problems?select=id,title,category,status,confidence,impact_score,updated_at&region_id=eq.${encodeURIComponent(region.id)}&order=updated_at.desc&limit=50`)}catch{}
 try{reports=await q(`/rest/v1/human_reports?select=id,title,category,verification_status,created_at&region_id=eq.${encodeURIComponent(region.id)}&order=created_at.desc&limit=12`)}catch{}
 try{children=await q(`/rest/v1/regions?select=id,name,level,admin_code_pum&parent_id=eq.${encodeURIComponent(region.id)}&order=name.asc&limit=100`)}catch{}
 const problemHtml=problems.length?problems.map(p=>`<article class="region-problem"><div><h3>${esc(p.title)}</h3><p>${esc(p.category||'Masalah publik')} · ${esc(p.status||'open')} · diperbarui ${p.updated_at?new Date(p.updated_at).toLocaleDateString('id-ID'):'—'}</p><div class="problem-meta"><span>Confidence ${esc(p.confidence??'—')}</span><span>Impact ${esc(p.impact_score??'—')}</span></div></div><button class="btn-outline" data-problem-id="${esc(p.id)}">Lihat detail →</button></article>`).join(''):'<div class="empty">Belum ada masalah publik yang langsung dipetakan ke wilayah ini.</div>';
 const reportHtml=reports.length?reports.map(r=>`<div class="evidence-row"><b>${esc(r.title)}</b><small>${esc(r.category||'Laporan warga')} · ${esc(r.verification_status||'received')} · ${r.created_at?new Date(r.created_at).toLocaleDateString('id-ID'):''}</small></div>`).join(''):'<div class="empty">Belum ada laporan warga yang terhubung.</div>';
 const childHtml=children.length?children.map(c=>`<button class="suite-row suite-button" data-region-action="region" data-arg="${esc(c.name)}"><div><b>${esc(c.name)}</b><small>${esc(c.level||'Wilayah')} · ${esc(c.admin_code_pum||'')}</small></div><span>→</span></button>`).join(''):'<div class="empty">Daftar wilayah turunan belum tersedia.</div>';
 $('region-detail').innerHTML=`<div class="region-head"><div><span class="public-kicker">${esc(region.level||'WILAYAH INDONESIA')}</span><h1>${esc(region.name)}</h1><p>Kode wilayah ${esc(region.admin_code_pum||'—')} · sumber ${esc(region.source_name||'registry publik')}</p></div><span class="region-count">${problems.length} masalah</span></div><div class="region-kpis"><div><small>MASALAH</small><b>${problems.length}</b></div><div><small>LAPORAN WARGA</small><b>${reports.length}</b></div><div><small>WILAYAH TURUNAN</small><b>${children.length}</b></div><div><small>STATUS DATA</small><b>Publik</b></div></div><div class="region-grid"><section><h3>Masalah di wilayah ini</h3><div class="region-problems">${problemHtml}</div></section><aside><h3>Laporan warga</h3>${reportHtml}<h3 class="region-subhead">Wilayah turunan</h3>${childHtml}</aside></div><div class="detail-actions"><button class="btn-outline" data-region-action="problems">← Semua masalah</button><button class="btn-primary" data-region-action="report" data-arg="${esc('Informasi wilayah '+region.name)}">Laporkan informasi wilayah</button></div>`;wire();
 }catch(err){$('region-detail').innerHTML=`<div class="suite-status warn">${esc(err.message)}</div><button class="btn-outline" data-region-action="problems">Kembali ke masalah</button>`;wire()}}
window.openPublicRegion=name=>renderRegion(name);window.renderPublicRegion=renderRegion;
const old=window.render;window.render=async function(v,x=''){if(v==='region')return renderRegion(x);return typeof old==='function'?old(v,x):undefined};
const style=document.createElement('style');style.textContent=`.public-region-page{max-width:1180px;margin:0 auto}.region-head{display:flex;justify-content:space-between;gap:20px;background:#fff;border:1px solid #e1e9f1;border-radius:15px;padding:20px}.region-head h1{font-size:28px;margin:6px 0}.region-head p{color:#718198;font-size:11px}.region-count{align-self:flex-start;padding:7px 10px;border-radius:999px;background:#edf5ff;color:#276bb2;font-size:10px;font-weight:800}.region-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin:10px 0}.region-kpis>div{background:#fff;border:1px solid #e1e9f1;border-radius:12px;padding:13px}.region-kpis small{display:block;color:#8795a7;font-size:8px}.region-kpis b{display:block;font-size:17px;margin-top:4px}.region-grid{display:grid;grid-template-columns:1.6fr 1fr;gap:10px}.region-grid section,.region-grid aside{background:#fff;border:1px solid #e1e9f1;border-radius:13px;padding:16px}.region-grid h3{font-size:14px;margin:0 0 10px}.region-problems{display:grid;gap:8px}.region-problem{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:12px;border:1px solid #e7edf3;border-radius:11px}.region-problem h3{margin:0 0 4px;font-size:12px}.region-problem p{margin:0;color:#7c8a9d;font-size:9px}.region-subhead{margin-top:18px!important}.suite-button{width:100%;text-align:left;background:#fff;border:1px solid #e7edf3;cursor:pointer}.suite-button:hover{background:#f7fbff}@media(max-width:700px){.region-head{display:block}.region-kpis{grid-template-columns:1fr 1fr}.region-grid{grid-template-columns:1fr}.region-problem{grid-template-columns:1fr}.region-problem .btn-outline{justify-self:start}}`;document.head.appendChild(style);
})();
