const BMKG='https://api.bmkg.go.id/publik';
async function json(url){const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
function parseXml(xml){const out=[];for(const b of (xml.match(/<item\\b[\\s\\S]*?<\\/item>/gi)||[]).slice(0,60)){const g=t=>{const m=b.match(new RegExp('<'+t+'(?:[^>]*)>([\\s\\S]*?)<\\/'+t+'>','i'));return m?m[1].replace(/<!\\[CDATA\\[|\\]\\]>/g,'').replace(/<[^>]+>/g,'').trim():''};const title=g('title'),link=g('link'),description=g('description'),pub=g('pubDate');if(title&&link)out.push({title,link,description,published_at:pub?new Date(pub).toISOString():null})}return out}
function pick(o,keys){for(const k of keys)if(o?.[k]!=null&&String(o[k]).trim())return o[k];return null}
export default async function handler(req,res){
 if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});
 if(req.query.mode==='incidents'){
  const rows=[];
  try{const d=await json('https://data.bmkg.go.id/DataMKG/TEWS/autogempa.json');const g=d?.Infogempa?.gempa;if(g){const la=String(g.Lintang||''),lo=String(g.Bujur||'');const a=parseFloat(la),b=parseFloat(lo);rows.push({source_name:'BMKG',source_type:'official_seismic',source_url:'https://data.bmkg.go.id/gempabumi/',title:'Gempa '+(g.Magnitude||'')+' '+(g.Wilayah||''),description:'Magnitudo '+(g.Magnitude||'')+', kedalaman '+(g.Kedalaman||'')+', '+(g.Potensi||''),incident_type:'Gempa Bumi',status:'official_signal',observed_at:new Date().toISOString(),latitude:/LS/i.test(la)?-Math.abs(a):a,longitude:/BB/i.test(lo)?-Math.abs(b):b,location_text:g.Wilayah||'',severity:Number(g.Magnitude)>=6?'high':Number(g.Magnitude)>=5?'medium':'low',confidence_score:.99,location_precision:'exact'})}}catch{}
  try{const u='https://gis.bnpb.go.id/server/rest/services/Kejadian_Bencana_Mingguan/FeatureServer/0/query?where=1%3D1&outFields=*&returnGeometry=true&f=json&resultRecordCount=100&orderByFields=objectid%20DESC';const d=await json(u);for(const f of (d.features||[])){const a=f.attributes||{},g=f.geometry||{};const lat=Number(g.y),lng=Number(g.x);if(!Number.isFinite(lat)||!Number.isFinite(lng))continue;const title=pick(a,['kejadian','jenis_bencana','jenis','nama_bencana'])||'Kejadian bencana';const loc=pick(a,['lokasi','Location','lokasi_kejadian','alamat'])||'';rows.push({source_name:'BNPB',source_type:'official_disaster',source_url:'https://gis.bnpb.go.id/server/rest/services/Kejadian_Bencana_Mingguan/FeatureServer/0',external_id:String(pick(a,['id','kode_bencana','objectid'])||''),title:String(title),description:String(pick(a,['kronologi','deskripsi','keterangan'])||loc),incident_type:String(title),status:'official_signal',observed_at:new Date().toISOString(),latitude:lat,longitude:lng,location_text:loc,severity:'unknown',confidence_score:.95,location_precision:'exact'})}}catch{}
  for(const u of ['https://www.antaranews.com/rss/terkini.xml','https://www.antaranews.com/rss/metro-kriminalitas.xml','https://www.antaranews.com/rss/nusantara.xml']){try{const r=await fetch(u,{headers:{Accept:'application/rss+xml,application/xml,text/xml'}});if(!r.ok)continue;for(const n of parseXml(await r.text())){if(!/(kebakaran|kecelakaan|banjir|longsor|gempa|erupsi|ledakan|tenggelam|tabrakan|darurat)/i.test(n.title+' '+n.description))continue;rows.push({source_name:'ANTARA RSS',source_type:'news_signal',source_url:n.link,title:n.title,description:n.description||'',incident_type:(n.title.match(/kebakaran|kecelakaan|banjir|longsor|gempa|erupsi|ledakan|tenggelam|tabrakan|darurat/i)||['Peristiwa'])[0],status:'unverified',observed_at:n.published_at||new Date().toISOString(),published_at:n.published_at,latitude:null,longitude:null,location_text:'Lokasi perlu diverifikasi dari sumber berita',severity:'unknown',confidence_score:.55,location_precision:'unknown'})}}catch{}}
  res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=600');return res.status(200).json({source:'BMKG + BNPB + ANTARA RSS',generated_at:new Date().toISOString(),incidents:rows});
 }
 const adm4=String(req.query.adm4||'').trim();if(!/^\\d{2}\\.\\d{2}\\.\\d{2}\\.\\d{4}$/.test(adm4))return res.status(400).json({error:'adm4 must be an Indonesian level-IV administrative code'});
 try{const data=await json(BMKG+'/prakiraan-cuaca?adm4='+encodeURIComponent(adm4));res.setHeader('Cache-Control','s-maxage=900, stale-while-revalidate=1800');return res.status(200).json({source:'BMKG',attribution:'Badan Meteorologi, Klimatologi, dan Geofisika',generated_at:new Date().toISOString(),data})}catch{return res.status(502).json({error:'BMKG unavailable'})}
}