const BASE='https://gfggmkeucgqkkyvummpu.supabase.co/functions/v1/public-portal-api';
const SB='https://gfggmkeucgqkkyvummpu.supabase.co/rest/v1/regions?select=id,name,level,latitude,longitude&level=in.(province,regency)&is_active=eq.true&limit=1000';
const KEY='sb_publishable_ptCVbq9h15prKhT0OO5Zmg_LkE3cb0';
function parse(xml){const out=[];for(const b of (xml.match(/<item\\b[\\s\\S]*?<\\/item>/gi)||[]).slice(0,50)){const g=t=>{const m=b.match(new RegExp('<'+t+'(?:[^>]*)>([\\s\\S]*?)<\\/'+t+'>','i'));return m?m[1].replace(/<!\\[CDATA\\[|\\]\\]>/g,'').replace(/<[^>]+>/g,'').trim():''};const title=g('title'),link=g('link'),description=g('description'),pub=g('pubDate');if(title&&link)out.push({title,link,description,published_at:pub?new Date(pub).toISOString():null})}return out}
function matchRegion(text,regions){const s=String(text||'').toLowerCase();let best=null;for(const r of regions){const n=String(r.name||'').toLowerCase();if(n.length>3&&s.includes(n)&&(!best||n.length>String(best.name).length))best=r}return best}
export default async function handler(req,res){
 if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});
 if(req.query.live==='1'){
  try{const rr=await fetch(SB,{headers:{apikey:KEY,Authorization:'Bearer '+KEY,Accept:'application/json'}});const regions=rr.ok?await rr.json():[];const rows=[];for(const u of ['https://www.antaranews.com/rss/terkini.xml','https://www.antaranews.com/rss/metro-kriminalitas.xml','https://www.antaranews.com/rss/nusantara.xml','https://news.google.com/rss/search?q=kebakaran+OR+kecelakaan+OR+banjir+OR+longsor+Indonesia&hl=id&gl=ID&ceid=ID:id']){try{const r=await fetch(u,{headers:{Accept:'application/rss+xml,application/xml,text/xml'}});if(!r.ok)continue;for(const n of parse(await r.text())){const text=n.title+' '+n.description;if(!/(kebakaran|kecelakaan|banjir|longsor|gempa|erupsi|ledakan|tenggelam|tabrakan|darurat)/i.test(text))continue;const rg=matchRegion(text,regions);rows.push({source_name:u.includes('google.com')?'Google News':'ANTARA RSS',source_type:'news_signal',source_url:n.link,title:n.title,description:n.description||'',incident_type:(n.title.match(/kebakaran|kecelakaan|banjir|longsor|gempa|erupsi|ledakan|tenggelam|tabrakan|darurat/i)||['Peristiwa'])[0],status:'unverified',observed_at:n.published_at||new Date().toISOString(),latitude:rg?.latitude||null,longitude:rg?.longitude||null,location_text:rg?.name||'Lokasi belum teridentifikasi',severity:'unknown',confidence_score:.5,location_precision:rg?'region_centroid':'unknown'})}}catch{}}res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=600');return res.status(200).json({source:'ANTARA RSS + Google News RSS',generated_at:new Date().toISOString(),incidents:rows.slice(0,100)})}catch(e){return res.status(502).json({error:'Live news unavailable',message:e.message})}
 }
 const q=String(req.query.q||'').trim();if(!q)return res.status(400).json({error:'q is required'});try{const r=await fetch(BASE+'?action=search&q='+encodeURIComponent(q));const text=await r.text();res.status(r.status);res.setHeader('Content-Type','application/json');return res.send(text)}catch(e){return res.status(502).json({error:'Search unavailable',message:e.message})}
}